### PR TITLE
Use the notice component instead of the b-alert

### PR DESCRIPTION
**Pull request by JayyajGH**
This PR is basically to replace the b-alert with a notice-message component.

The reason this was tricky was because the edit dropdown on the card was floated to the right but the alert component had a higher z index so was shown over it.  The notice component didn't and so the dropdown displayed over it.

Basically I've refactored the news section to use dynamic components and now it only displays the dropdown if the news type is known.

Thoughts, suggestions and abuse please.... :-)

### CODE REVIEW

**Comment by edwh** [comment]
I'm a bit surprised we couldn't fix that by setting different z-index values, but you must have considered that.

The alert is really there to spot a coding error while developing the site, and could be dropped once I'm confident I've done them all.  So it depends a bit on whether dynamic component names are a good thing or a bad thing?  I doubt that they'll be as easy to find in an IDE, for example, and it forces us to pass the same props to each.

@nicksellen , do you have a view on that?

**Comment by JayyajGH** [comment]
Yeah we could have fixed it with adding a z-index but I assumed that we didn't actually want the dropdown menu to appear when the news type wasn't recognised.  It would be wrong to use z-index just to hide the dropdown behind the message and not great for accessibility.

My main change was then to only display the components and dropdown for recognised news types.  In doing that I created a function to check what was valid.  This logic was then duplicated.  The function had a list of valid types and the html had the actual list of valid types.  So there was a duplication and a disconnect so they could potentially become out of sync.  Now they are both driven off the same data.

At the moment all of those components have the same props.  If that wasn't the case then this wouldn't be so clean.

I thought the dynamic components might prompt a discussion. :-)

**Comment by nicksellen** [comment]
I think the dynamic component is a big improvement of the tangle of ifs.

I would put it in it's own component though, and consider using a render function, see https://vuejs.org/v2/guide/render-function.html.

Inside it you can do something like:
```js

// import all the news component variants first ...

const types = {
        AboutMe: NewsAboutMe,
        Message: NewMessage,
        CommunityEvent: NewsCommunityEvent,
        VolunteerOpportunity: NewsVolunteerOpportunity,
        Story: NewsStory,
        Alert: NewsAlert,
        NoticeBoard: NewsNoticeboard
}

export default {
  functional: true,
  render (createElement, { data, children }) {
    return createElement(types[data.props.variant], data, children)
  }
}
```

**Comment by edwh** [comment]
Ok, let's do that.

There may be other cases of this, for example in chat.

------ Original Message ------

**Comment by JayyajGH** [comment]
Yeah moving it into a component might be nicer.  I usually prefer the HTML of all my pages/components to fit on one page.

What do we gain from using a render function? I think I'm still from the non-React world where I still prefer using HTML over Javascript to create elements.  I'm not against it.  I'm just trying to understand the advantage.  I've only ever used render functions to create elements where I didn't know the type upfront.

The other thing of interest is that the component also needs to contain the dropdown and notice message as it is all driven off the same data.  That might make using a render function a bit messy.

**Comment by nicksellen** [comment]
> What do we gain from using a render function?

To me, if there is some programmatic logic for which component/element it should be, then a render function is a nice idea. To me, it seems a  bit pointless having a template which only would contain a dynamic `<component :is=...` element, not really much of a template! I would not object to that though, also seems fine :)

> The other thing of interest is that the component also needs to contain the dropdown and notice message as it is all driven off the same data. That might make using a render function a bit messy.

Yes, I think in that case, I wouldn't use a render function, and `<component :is=...` is a good idea when there is other stuff in the template. Also, consider slots if you need other things inside it that can be defined in the parent template, if you don't know about them, worth understanding them, very powerful!

**Comment by JayyajGH** [comment]
Thanks Nick.  Yeah I can see your point.  I'm not particularly bothered either way in the case you mention.  I'll put the logic into a component and lets take a look.  I did consider slots first here but each component was so different it didn't seem that suitable.

I've got quite a lot on over the next week so I'll be dipping in and out of freegle.  I should be able to get to this tomorrow though.

**Comment by edwh** [comment]
Thanks.  I think packing does kinda take  priority.

**Comment by JayyajGH** [comment]
Gonna be without internet for a while (again) too. :-(

**Comment by edwh** [comment]
After I last moved, it took me four years of a community project 
persuading farmers to let us run fibre optic cables across their fields 
before I got decent broadband.

1Gbps symmetric for £30/month now, though, so it was worth it.

------ Original Message ------

**Comment by JayyajGH** [comment]
@edwh  - What is the purpose of the button-content slot template in NewsThread.vue?  Is it just a cut-and-paste thing and can be removed or am I missing something?

**Comment by edwh** [comment]
From memory it was adding a space into the button and I added that in so 
that it would just have the dropdown arrow and align more prettily.

I could be wrong about that memory.

------ Original Message ------

**Comment by JayyajGH** [comment]
Ah ok.  I'll take a look when I'm somewhere I can test the changes.

**Comment by JayyajGH** [comment]
I've been having a quick look at refactoring this PR this morning.  It actually appears that the majority of the NewsThread component is related to this change.  I've tried pulling out the related stuff into a separate component and it actually takes the majority of the original file with it.  Most of the methods etc. are called from this area.

Here's my suggestion...
1. We merge this PR as it is.  It gets rid of a TODO and makes things tidier.
2. I try and refactor the NewsThread component to take out the "Leave a comment" stuff.  This should leave the code related to this PR in this file.  That feels like the best refactor to start with and we can progressively improve it.

Thoughts?

**Comment by edwh** [comment]
1 sounds reasonable.

On 2, have you picked up on the difference between reply to a thread and 
reply to a reply?

------ Original Message ------

**Comment by JayyajGH** [comment]
To be honest I haven't looked into it that far yet.  Is that all dealt with in the card footer?

**Comment by edwh** [comment]
It's inside the card footer in NewsThread, and then there is similar but 
different code inside NewsReply to deal with the reply to reply stuff.

It would be possible to extract the reply function out into a separate 
component, but I think if we did then the component ought to also 
support the similar but different reply function from NewsReply.

That it doesn't feel urgent to me, and some of it is a bit subtle, so 
I'm not sure it's a good thing to do just at the moment.

------ Original Message ------

**Comment by JayyajGH** [comment]
OK.  Maybe I'll just add a TODO to that effect then.  I'll do that now.

**Comment by JayyajGH** [comment]
Could we just take the whole footer out into a separate component?  That would simply both areas nicely and would be a quick first step.

**Comment by edwh** [comment]
I'd rather not.  Then we'd have a situation where the reply was inside 
the NewsReply component but not inside the NewsThread component.  I 
don't find NewsThread too large.  Bung a TODO MINOR in then we can get 
this one merged.

------ Original Message ------

**Comment by JayyajGH** [comment]
Yeah that's fair enough.  TODO added.

**Comment by edwh** [comment]
Ok for me to look at merging?

------ Original Message ------

**Comment by JayyajGH** [comment]
Yup.  Good to go...

**Pull request merged**
