### PR TITLE
Use the profile component

### PR DESCRIPTION
**Pull request by JayyajGH**
Here is another set of refactoring to use the profile image component. 

THESE ARE CURRENTLY UNTESTED

 Is there an easy way to test them?

### CODE REVIEW

**Comment by edwh** [comment]
You can test chat by setting up a test user with an email/password 
login, and messaging another test user (or real one).  You can post test 
messages on FreeglePlayground groups to reply to.

It's ok to post test stuff on chitchat - there's a dropdown option on 
the top right to delete a thread once you're done.  Don't leave them 
around for too long (e.g. overnight) else we'll mail them out to people.

------ Original Message ------

**Comment by JayyajGH** [comment]
I managed to test the chat stuff by posting an offer in the playground group and a nice lady called Elaine starting replying to it. :-)

So it's ok just to post a test message on chitchat in my (live) local group for example?

How do I test the modmail stuff?  I'm guessing I need a message from a moderator?

**Comment by edwh** [comment]
Elaine is a lovely volunteer in Penrith.

ChitChat is geographical, so by default people only see stuff near them.  It's fine for you to clutter chitchat with stuff as long as it isn't left for too long. 

If you post something then I will reject it and you should then see a modmail. 

------ Original Message ------

**Comment by JayyajGH** [comment]
I`ve just made a post - Would you be able to reject it please.

**Comment by edwh** [comment]
I can't see it on the playground group.  Which email is on the account, 
and which community did you post to?

------ Original Message ------

**Comment by JayyajGH** [comment]
It`s on chitchat.  The post will be from jayyaj¬hotmail.com  Posted to the "Bishopston" community

**Comment by JayyajGH** [comment]
I think the community is probably the "Bristol" community rather then "Bishopston".  Sorry!

**Comment by edwh** [comment]
Ok - please withdraw that and only send test posts to the Playground 
group (you can select it from the dropdown).  Volunteers on other groups 
will get confused, otherwise, and I don't have immediate access to 
moderate posts on other groups.

------ Original Message ------

**Comment by JayyajGH** [comment]
> You can test chat by setting up a test user with an email/password login, and messaging another test user (or real one). You can post test messages on FreeglePlayground groups to reply to. It's ok to post test stuff on chitchat - there's a dropdown option on the top right to delete a thread once you're done. Don't leave them around for too long (e.g. overnight) else we'll mail them out to people.


Post deleted.

I must have misunderstood your message above then.  You said it was ok to post test stuff on chitchat as long as you delete it fairly quickly.  What did you actually mean then?  Where should I post stuff to test the "comment on comment" type functionality?

**Comment by edwh** [comment]
Sorry, I am being unclear.

You wanted a modmail type message in chat; that happens when an 
OFFER/WANTED post is rejected.  To make that happen, post a test OFFER 
onto the FreeglePlayground community, and then I'll reject it.  Then 
you'll get that kind of chat message.

Posting on chitchat is indeed fine as long as you delete it quickly.  
Posts on chitchat aren't much moderated and don't related to the modmail 
type chat messages.

------ Original Message ------

**Comment by JayyajGH** [comment]
Ok cool. That makes sense!

I`ve just posted a test offer in the playground group so if you could reject that one that would be great.

**Comment by JayyajGH** [comment]
Thanks!  Finally got there.  Right this PR is now good to go!  I`ve just found a pile more profile images but I`m not on holiday until mid next week so I`ll get to them soon if I don`t get a chance today.

**Pull request merged**
