### PR TITLE
Allow the image to be accessed via the keyboard

### PR DESCRIPTION
**Pull request by JayyajGH**
Something I noticed when looking into the freegled stuff.  You couldn't expand the image using the keyboard as it didn't have a tabstop or any keyboard event.

### CODE REVIEW

**Comment by JayyajGH** [comment]
Actually hold off on this one for a bit.  I think maybe making it a button with an included image would be a better option and then we're not fighting HTML.

**Comment by JayyajGH** [comment]
OK I've now made this a button.  There wasn't some crazy reason why this needed to be a div was there?

This change is all part of showing the freegled items.  I'm currently trying to find the best way to stop clicks/keyboard interaction on a freegled item and the image was causing issues.  Fundamentally it's because a button wouldn't smell any sweeter if it was a div.  In fact you would need to add an artificial smell to it.

**Comment by edwh** [comment]
I don't think there was any reason for it not to be a button.  And as 
you point out, any such reason would be crazy.

------ Original Message ------

**Comment by JayyajGH** [comment]
Some might also say that removing auto-capitalisation from a control to make it work on Safari would be crazy too...

**Comment by JayyajGH** [comment]
So this one is now good to go.  Definitely worth you taking a look though to check I haven't missed anything.  It should now have tabbing and keyboard control out of the box.

**Comment by edwh** [comment]
Checked it out, had a play, looks good.

**Pull request merged**
