### PR TITLE
Feature/add header to page

### PR DESCRIPTION
**Pull request by JayyajGH**
A small fix I noticed when playing with Wave.  The chat page didn't have a main H1 header.  I've had to add a container to the page to keep Vue and it's one-root-element checking happy.  I think bootstrap rows are supposed to be in containers anyway.

### CODE REVIEW

**Comment by edwh** [comment]
Do you really need the b-row round the h1?  If so, then is it valid to have it without a b-col?

**Comment by JayyajGH** [comment]
I could get away with not having the row actually.  I seem to remember that you didn't have to have columns or the container but I can't remember.  I only added the container for the single root element - client only doesn't seem to count.
So yes, I think I'll remove the row.

**Comment by JayyajGH** [comment]
Done...

**Comment by edwh** [comment]
I've got loads with just a top-level div; I'm not sure b-container adds 
that much, really.  But since you opened my eyes to the wonder of flex 
and grid I'm trying to get away from using rows/columns where possible.

------ Original Message ------

**Comment by JayyajGH** [comment]
Yeah the container is probably not strictly necessary.  It just ends up being a div with width 100% anyway.  So basically a regular div.

Ah grid and flex... :-)

**Pull request merged**
