### PR TITLE
Enhancements/refactor duplicated code in message

### PR DESCRIPTION
**Pull request by JayyajGH**
The start of some work to remove the duplication of code in the Message.vue component

### CODE REVIEW

**Comment by edwh** [comment]
I think  `:display-message-link="true"` is better as display-message-link - Nick pointed me at [this](https://vuejs.org/v2/guide/components-props.html#Passing-a-Boolean) earlier.

Does the default of the groups prop need to be a function for some reason?

**Comment by JayyajGH** [comment]
:point="true". Or should I say "point". :-)  Good spot.

**Comment by JayyajGH** [comment]
I lifted the groups prop definition straight from the original parent component.  Not sure why that was done originally so I just replicated it.

**Comment by edwh** [comment]
I can't imagine a reason.  If that's the worst grunge in the code we can live with it.

**Comment by JayyajGH** [comment]
A belated comment re the groups prop....

This comment:
 // Object or array defaults must be returned from a factory function

is from here:
https://vuejs.org/v2/guide/components-props.html

So it looks like the default of an object or array should be a function

**Comment by edwh** [comment]
Aha.

**Pull request merged**
