### PR TITLE
Convert another piece of functionality to use the notice component

### PR DESCRIPTION
**Pull request by JayyajGH**

### CODE REVIEW

**Comment by edwh** [comment]
Thanks.  What's the click.native change for, so that I understand it?

------ Original Message ------

**Comment by JayyajGH** [comment]
Responding to a native event on a "normal" element like a div you just use @click.  A custom component event handler will only listen to custom events from the component by default.  .native says listen to native events as well.

**Comment by JayyajGH** [comment]
[](https://vuejs.org/v2/guide/components-custom-events.html)

**Comment by edwh** [comment]
Thanks, that's good to know. Will merge.

**Pull request merged**
