### PR TITLE
Don't fix the height of the donate message

### PR DESCRIPTION
**Pull request by JayyajGH**
Here is an option for fixing this issue.  If this is acceptable then I'll confirm the PR.

### CODE REVIEW

**Comment by aaronferris** [comment]
Code looks OK but I'm always apprehensive about set fixed heights, makes the content very inflexible, especially when someone starts playing with the font size of their browser.

**Comment by JayyajGH** [comment]
Yeah it can look a bit odd.  With overflow: hidden it cuts off the text halfway through as well.  I've not touched the job listings though so they work as they did before - with a fixed height.  I've just removed the fixed height from the donate message so the whole thing shows to fix the issue listed on Slack.

**Comment by edwh** [comment]
Just removing the jobbox CSS entirely seems to work ok for me.  I think I had some idea that the top box of jobs would be scrollable, but it doesn't seem necessarily.  Does that look ok to you?

**Comment by JayyajGH** [comment]
I'm guessing if there are a lot of jobs then it would take up too much of the screen though.  How many jobs could the API return?  Maybe we bin the max-height and put a max on the number to display of 3 for example.

**Comment by edwh** [comment]
It will display 5 here by default, so it's bounded.

------ Original Message ------

**Comment by JayyajGH** [comment]
At the moment it looks like 3 will fit in the space allocated.  This takes up about 1/2 of the screen.  Would 5 be too much?  Should we restrict it to 3 and remove the max-height?

**Comment by edwh** [comment]
Or maybe add classes to the bottom two to hide them on small screens?

------ Original Message ------

**Comment by edwh** [comment]
Something like this seems to work ok, and the same for recently viewed.

```
      <div v-for="(job, index) in jobs" :key="'job-' + job.onmousedown" class="">
        <Job :summary="true" :job="job" :class="index > 1 ? 'd-none d-md-block' : ''" />
      </div>
```

I'll push that, I think.  Fixes the donate button and also is less of a screen hog on mobile.

**Comment by JayyajGH** [comment]
Ok cool.

**Comment by JayyajGH** [comment]
Shall I just delete this PR?

**Comment by edwh** [comment]
Yeah, I'll push the fix.  Thanks, though, it's doing this PR that got a 
fix, even if it's a different fix.

------ Original Message ------

**Comment by JayyajGH** [comment]
A belated comment on this @edwh 

What is the Freegle traffic split on desktop/tablet/mobile?  By doing this are we chopping out a load of revenue from mobile?

**Comment by edwh** [comment]
It's about 50/50.  The purpose of the box at the top is not so much 
because the specific jobs we choose to show there will be ones people 
click on (that's unlikely).  It's to show them that there are jobs and 
encourage them to click to see more of them.

  But realistically most of our job ad revenue is likely to come from 
larger devices than small phones.

------ Original Message ------

**Comment by JayyajGH** [comment]
As an alternative solution, on small devices we could show a box with a link to jobs instead of showing the jobs themselves.

**Comment by edwh** [comment]
We could, but I think specific examples are what would prompt people to 
click.  Otherwise half of them will misinterpret it as "Jobs with 
Freegle" and ignore it.

....but classic case of something to actually trial once I have some 
bandit testing infrastructure.


------ Original Message ------

**Comment by JayyajGH** [comment]
That makes sense.  Yeah definitely a perfect example of an A/B test requirement.

**Pull request closed without merging**
