### PR TITLE
Ensure list items used as nav-items do not have a bullet points.

### PR DESCRIPTION
**Pull request by bernhard-hofmann**
Ensure list items used as nav-items do not have a bullet point. Fixes bullet point shown beside the `Sign In` button on smaller screens.

### CODE REVIEW

**Comment by edwh** [comment]
The fix works - thanks - but I think it would be better implemented using existing BootstrapVue classes.  Probably the ul/li which contains this button should be a b-navbar-nav/b-nav-item; we shouldn't really be using raw uls.  Could you adapt for that?

**Comment by bernhard-hofmann** [comment]
I didn't make the `ul` or `li` and assumed whoever did intended it to be that way.

Should the contributor guidelines include seeking direction on changes before submitting a PR to avoid these misunderstandings?

**Comment by edwh** [comment]
I did the original, but it was probably copied from the older code and I 
failed to change it.

Not sure what the contributor guidelines would say?  "Don't assume that 
something that looks wrong is there for a good reason unless there's a 
comment"?

------ Original Message ------

**Comment by edwh** [comment]
I've done a checkin which should fix this.  Thanks for spotting it.

**Pull request closed without merging**
