### PR TITLE
Feature/add accessible regions

### PR DESCRIPTION
**Pull request by JayyajGH**
Some more accessibility stuff.  Add header, main and aside regions.

### CODE REVIEW

**Comment by JayyajGH** [comment]
The only oddity here is how to mark up the pseudo-footer. i.e. the one with the links and social media links on the sidebar.  It's not really an aside and it's not really a footer.  It does contain a lot of useful links that aren't really available elsewhere so I think it qualifies as a nav element.

**Comment by edwh** [comment]
Is this merged?  There are a bunch of changes to default.vue.

**Comment by JayyajGH** [comment]
It was up to date but probably isn't now after the nchan stuff has gone to master.  Although github thinks it is...  I'll check

**Comment by JayyajGH** [comment]
Well git is obviously cleverer than I thought as it was completely happy sorting out that merge by itself.

**Comment by JayyajGH** [comment]
So this is now good to go...

**Pull request merged**
