### PR TITLE
Remove the bootstrap rows/cols to fix the mobile shimmy

### PR DESCRIPTION
**Pull request by JayyajGH**
Fix the mobile row/col issue shimmy on the give page.

### CODE REVIEW

**Comment by edwh** [comment]
I haven't checked (off to the vet) but may apply to /find/whatnext too?

------ Original Message ------

**Comment by JayyajGH** [comment]
Oh yeah it does.  We really need to create a common component for these...  I'll sort that one as part of this PR.

Good luck at the vets!

**Comment by JayyajGH** [comment]
Fixed on find as well as give now

**Comment by edwh** [comment]
Shall I take this now?  Shared component could come later, as there may 
be wrinkles.



------ Original Message ------

**Comment by JayyajGH** [comment]
Yup now is good.  Unless you can think of anything weird on this page...  I've only tested this in Chrome.

**Comment by edwh** [comment]
The more I learn, the more I feel I want everything that's part of bootstrap apart from the layout.

**Comment by JayyajGH** [comment]
That's an option though.  You can just bring in the stuff you need can't you?  Sounds like you want something halfway between tailwind and bootstrap.  I think now we have flexbox and grid as part of CSS, it's probably easier to use than the bootstrap implementation.  I think the JS frameworks will go the same way.  Same as things like Sass.  They are slowly becoming obsolete as the basic tools are getting better.

**Comment by edwh** [comment]
Yes, you can do that.  And when I first used bootstrap it was from a 
position of knowing very little CSS and wanting a way to produce a 
responsive layout without really understanding what I was doing.  It did 
the job for that, it's not bootstrap's fault if I've got marginally more 
knowledgeable.

------ Original Message ------

**Comment by JayyajGH** [comment]
I guess that's the problem with any project that lasts more than about a year.  Things change and become out of date very quickly.  I've been trying to resolve an issue with C++ COM this morning.  Freegle will be fine. :-)  Freegle would probably still be in development if you had manually crafted everything!

**Comment by edwh** [comment]
https://en.wikipedia.org/wiki/Wittgenstein%27s_ladder

------ Original Message ------

**Comment by JayyajGH** [comment]
I've not heard that before but it's so true!  I doubt anyone would do a project the same way once they have finished it.  And no one every has time to go back and throw away the ladder.

**Comment by edwh** [comment]
Probably if we spoke to people who made ladders they'd do it all 
differently if they had the chance.

------ Original Message ------

**Comment by JayyajGH** [comment]
I was struggling putting up some plasterboard last night as I had nowhere to put my drill and screws when I was stood on it.  This morning I saw a ladder with a little holder for all those things.  Ladder creators are what we aspire to be. :-)

**Comment by edwh** [comment]
I tell you something that's due a v2.  Wheels.

------ Original Message ------

**Comment by JayyajGH** [comment]
We've had enough time...

**Comment by edwh** [comment]
https://www.quora.com/How-many-alternatives-to-the-wheel-are-there

------ Original Message ------

**Comment by JayyajGH** [comment]
The screw drive one is really interesting.  Not sure how efficient that would be though!

**Comment by edwh** [comment]
It would be important to consider the direction of the thread on each 
side carefully.

------ Original Message ------

**Pull request merged**
