### PR TITLE
Enhancements/add error page

### PR DESCRIPTION
**Pull request by JayyajGH**
It doesn't look pretty at the moment but can I get your input on wording please @edwh

### CODE REVIEW

**Comment by edwh** [comment]
I might tweak the punctuation but it's basically fine, yes.

**Comment by JayyajGH** [comment]
I'm still on the hunt for a suitable image to use to finish this off at the moment.

**Comment by edwh** [comment]
With no copyright issues, of course.

------ Original Message ------

**Comment by JayyajGH** [comment]
Yeah that's the tricky bit.  Where did the video come from?  Can something be created with the same characters?

**Comment by edwh** [comment]
Yes, it probably could, actually - it comes from a friendly firm.  
Describe what you want and I'll ask them.

------ Original Message ------

**Comment by JayyajGH** [comment]
If we want to stick to the cartoony style then something like a confused man or someone tearing their hair out in similar style to the video.  I'm thinking something along the lines of the Pixar 404 page.

https://www.pixar.com/hfeature-films-launch

**Comment by edwh** [comment]
Yes, our friendly people will do one for us.  They are lovely.

------ Original Message ------

**Comment by JayyajGH** [comment]
Awesome!  It would be good to keep things in a similar style.

**Comment by edwh** [comment]
Here's one from the nice video people.

freegle 404 character

**Comment by JayyajGH** [comment]
Awesome.  I'll insert it into the new error page when I have a chance.

**Comment by JayyajGH** [comment]
OK what about something like this...

**Comment by JayyajGH** [comment]
At the moment it's the same image for all errors but with slightly different error text.

**Pull request merged**
