### PR TITLE
Move all remaining colour variables into the colour file.

### PR DESCRIPTION
**Pull request by JayyajGH**
Move a bunch more colours into the colour file.  I've not done any consolidation as part of this.  I've just moved their definitions into the common location.  It might be able time for us to see if we can chop any out.

### CODE REVIEW

**Comment by edwh** [comment]
There's certainly an argument that we have too many, isn't there?

**Comment by JayyajGH** [comment]
We do have quiet a lot! I think some consolidation would help to bring together the Freegle brand a bit more. Although in reality that's probably just marketing spiel and no one would actually notice. :-)

Probably the main advantage to us as developers and for developers new to the project, the benefit would be the simplicity of adding new elements.  What colour should I make this background?  Grey 1, 2, 3, 4 or 5?  And which one of the 8 blues should the foreground be?

It doesn't really matter whether the colours are coming from bootstrap or our own custom ones.  If we are using them then they are part of the project and therefore brand.  We're talking icing on the cake here I think but it's definitely worth doing at some point.

**Comment by aaronferris** [comment]
I think if we compared the colours, we'd find some are very similar to the naked eye so could be combined into a single variable. That's an assumption based on experience of a large number of variables.

Having a lot isn't a problem per se, so long as we're consistent in our usage of them.

IE: Links are colour $green, buttons are colour $red, <p> tags are $dark-grey etc. it becomes a problem when we start mixing and matching elements with different colours when their primary purpose is the same. IE links being a different colour one one page compared to the next page. More colour options = more likelihood of this happening.

It'll be time consuming as we need to be careful of regression but agreed with @JayyajGH it's worth doing at some stage.

**Comment by edwh** [comment]
We'd probably just have to start, have a look at some uses of colours, 
and build up a definition of what each is for.

Not sure when any of us will feel like that's the funnest thing to do 
today, though.

------ Original Message ------

**Comment by aaronferris** [comment]
No its not a 4:10pm job for sure, its a 'fresh set of eyes 9am with a coffee' job.

We might also want to consider implementing something like pattern labs in the future. 

https://github.com/pattern-lab/patternlab-php

It's basically a design guide, but you can use it for atomic designs, colours, layouts all sorts. Makes it very easy to see what images, colours etc are used in the site. That's a massive 'nice to have' though. Ive used it on projects in the past and found it very useful.

**Pull request merged**
