### PR TITLE
Style the bootstrap checkbox

### PR DESCRIPTION
**Pull request by JayyajGH**
Here is one option with regards to making the checkbox more obvious.

I've just styled the bootstrap version to be a bit bigger.  This would need some messing with alignment of the text too but I just thought I'd show you to see if you think it's any better than what is there currently.

### CODE REVIEW

**Comment by JayyajGH** [comment]
The other option would be to create our own checkbox style but that seems a bit overkill for a single checkbox and doing it the bootstrap way would keep the style consistent.

**Comment by edwh** [comment]
I've not looked at this, but I don't think bigger is sufficient.  We 
understand what checkboxes are, but if you think about it from scratch, 
a blank empty square is not a compelling call to action for someone who 
(genuinely) might never have seen one before.

------ Original Message ------

**Comment by JayyajGH** [comment]
My background has always been creating stuff for tech-savvy users and so this is a new area for me!  

Personally I thought that what you had already created was really good.  It draws your eye and the message is clear what you have to do.  I can't think of any way of doing this any better.  The only thing in my head in this scenario is to attempt to go back to skeuomorphic basics and try and recreate a toggle switch of some kind.  Bootstrap provides one of the Apple style sliders which might be more meaningful.

image

**Comment by edwh** [comment]
I wondered about that.  Decided against it.

Maybe just do a slightly nicer border, with shadow, check centring, make 
the arrow look less like ASCII art?

------ Original Message ------

**Comment by JayyajGH** [comment]
What about something like this?

This is actually really tricky!  The bootstrap checkbox is doing some weird stuff with positioning and font-sizes and so the usual alignment methods won't work.  This is a complete hack but it seems to work!

**Comment by edwh** [comment]
That's probably neater.  I'll take it.

Yes, I was rather befuddled by what Bootstrap was doing.

------ Original Message ------

**Pull request merged**
