### PR TITLE
Need to tell Vue this is an expression rather than a string

### PR DESCRIPTION
**Pull request by JayyajGH**
This was throwing a warning as it was being passed as a string without the v-bind

### CODE REVIEW

**Comment by edwh** [comment]
I consistently make this mistake - I wish there was a compile error for 
it.  Could we do anything with eslint or something?

If you search for "false" you'll find some other examples of the same 
bug, e.g.

<groupHeader v-if="group" :key="'groupheader-' + group.id" v-bind="group" show-join="false"/>

Would you be kind enough to review the others and fix them?

------ Original Message ------

**Comment by JayyajGH** [comment]
It is so easy to make!  I'm guessing if an eslint setting existed then it would probably be the default but I'll take a look.  The other option is just not to pass anything in which implies true. e.g. <component showJobOp>.  But obviously that doesn't work for false.
I'll see if I can find/fix any others...

**Comment by JayyajGH** [comment]
In pages/give/whatnext.vue there is this line:
      <groupHeader v-if="group" :key="'groupheader-' + group.id" v-bind="group" show-join="false" />
But showJoin isn't a prop on group header.  Is this an issue or work to do?

**Comment by nicksellen** [comment]
I don't think eslint can do any checks across files, so can't know the types of the components defined in other files.

There is a rule to enforce putting each prop on a new line (that we use in karrot) - https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/max-attributes-per-line.md - this makes it easier to see the props at a glance and in the example in this PR, it would be clearer to see the missing `:`, also helps keep clean diffs (as changing props mean just a line is changed).

**Comment by edwh** [comment]
I'd hope you could have a check which spotted "false" in double-quotes 
as a value to a prop which didn't have a : in front of it.  Regex stuff.

------ Original Message ------

**Comment by edwh** [comment]
I think that's work to do, but which is missing.  Good spot.  Can you 
add a TODO into GroupHeader?

------ Original Message ------

**Comment by JayyajGH** [comment]
Cool will do.  I can't actually find any others with this issue. There are a few going into external components but they would need to investigated individually I think as they might be correct.

**Comment by JayyajGH** [comment]
OK that should now be complete

**Comment by edwh** [comment]
It might just be that one, then.  Thanks for checking.

With "true" it has the same effect, of course.

------ Original Message ------

**Comment by JayyajGH** [comment]
Yeah I checked true as well.

**Comment by edwh** [comment]
Did you fix the invalid settings of the prop in the uses of GroupHeader, 
too?

------ Original Message ------

**Comment by JayyajGH** [comment]
Doh!  Talked about them.  In my head I was going to remove them.  Didn't.  One sec...

**Comment by JayyajGH** [comment]
Yes.  Yes I did. :-)

**Pull request merged**
