### PR TITLE
Add a bootstrap container to house the rows and columns

### PR DESCRIPTION
**Pull request by JayyajGH**
Bootstrap rows and columns should live in a bootstrap container.

https://bootstrap-vue.js.org/docs/components/layout/

### CODE REVIEW

**Comment by edwh** [comment]
Does this fix the margin issue, as per https://stackoverflow.com/questions/31885727/is-it-acceptable-to-omit-container-elements-when-using-bootstraps-grid ?

If so, then there will be quite a lot of other examples of this mistake.

**Comment by JayyajGH** [comment]
Nope not yet.  This was a standalone change so I thought I would get it in.

My general plan for this file is:
- Add container
- Move area options out of chitchat text box.  This will make it more related to where it is used and sort out the alignment on smaller screens.
- Sort out the photo box sizing
- Tidy up the rows and columns left behind - This will resolve the margin issue. I think the rows and columns just add unnecessary complexity here. Just making them bootstrap flexboxes will achieve the same effect with much less code and with none of the negative margin mess. Using negative margins to sort out the left and right hand spacing is one of the main issues that flexbox was designed to solve.

I also think that maybe creating a component with a slot to house this common layout which is definitely used in at least three separate components.  That will resolve the issue in a bunch of other places too.

**Comment by edwh** [comment]
All sounds good.  I'll merge this one.

------ Original Message ------

**Comment by JayyajGH** [comment]
It is quite convoluted way to get to the actual fix for the issue but I think it will tidy things up a lot on the way.  Honestly!

**Comment by edwh** [comment]
I believe you.  I've done a little fix for this issue, but don't let 
that put you off this, as it's a worthwhile change that will help stop 
me reaching for b-row all the time.

------ Original Message ------

**Comment by JayyajGH** [comment]
You fix doesn't appear to work for me btw.  It fixes the top section but the problem then occurs in the newsfeed section itself now.

**Comment by edwh** [comment]
Ah, ok.  Might look further then, might not.

------ Original Message ------

**Comment by JayyajGH** [comment]
It's the NewsUserIntro that is causing problems for me now.

**Pull request merged**
