### PR TITLE
Refactor the nchan logic into a mixin

### PR DESCRIPTION
**Pull request by JayyajGH**
Here it is... initially just for discussion

My main worries are around "me".  The "me" used in mounted needs to be re-defined as it won't pick up the "me" from the global mixin.  The other oddity is there is a watch over "me" as well.  This appears to work using the one from the me.js mixin but I'm a bit uncomfortable watching something that you are just assuming exists elsewhere.  Therefore I have added a local "me" property.

### CODE REVIEW

**Comment by edwh** [comment]
If you're worried about that, why not use a different name for me which won't clash with the global one?

**Comment by JayyajGH** [comment]
It wasn't the extra "me" that concerned me.  I just didn't like having the watch over "me" when there was no "me" defined in that component.  That is why I added a local one.  Does that make sense?

I think I prefer it with the same name.  Although I'm not sure which one takes precedence.  I know the components methods/properties take precedence over the mixins but not sure when there are multiple mixins.  I guess this is one of main reasons that mixins are considered bad.  I think this way, even if the global mixin wasn't around then this will still work.

**Comment by edwh** [comment]
I agree that it's clearer if you have a watch over a property that is 
defined in the component.  It's not simple to find out whether it is 
supposed to work, and therefore the code is more legible if we don't do 
that.

But I don't like the idea of doing that and then having a watch but not 
knowing which property it's watching on.

If the watch is working on the mixin property, then you don't need the 
local copy.

If the watch is working on the local copy, then clarity is improved by 
renaming it.

So I would favour renaming it and using a local copy.  Then nobody 
looking at the code in future is left confused over what's actually 
happening.

------ Original Message ------

**Comment by JayyajGH** [comment]
Yeah that makes sense. I agree. The watch does appear to work on the global mixin property but I don't like the idea of a component watching something in another component.  It's not very transparent.  I'll rename it.

**Comment by JayyajGH** [comment]
Tweaked and added some comments

**Comment by edwh** [comment]
This looks ok to me now. Undraft?

**Comment by JayyajGH** [comment]
I've undrafted but I need to sort out the merges next...

**Comment by JayyajGH** [comment]
Merge now complete so this is good to go

**Pull request merged**
