### PR TITLE
Use flex and margins to make the chat messages more flexible for long…

### PR DESCRIPTION
**Pull request by aaronferris**
… messages

### CODE REVIEW

**Comment by edwh** [comment]
Looks good, including on IE11.  Ta.

**Comment by JayyajGH** [comment]
@aaronferris @edwh 

A bit of a belated message on a closed PR but can the IE11 hack now be removed from this file?  The setting of the min-width on the media class.

**Comment by edwh** [comment]
I'll test that, but it'll be next week.

------ Original Message ------

**Comment by edwh** [comment]
Ah, yes, that CSS is referencing something which no longer exists.  So probably it gets shaken out but I'll remove it.

**Pull request merged**
