### PR TITLE
Update the login form fields to have an associated label.

### PR DESCRIPTION
**Pull request by JayyajGH**
So I've backtracked a little on the stuff I was doing on the login form.  There are potentially a lot of questions etc. in that area so I thought I would strip it down to basics and do a step at a time.

This change just updates the current input field with placeholder into an accessible input field with associated label.  Are you happy with this style?  The benefits you get here are:
- The field works correctly with a screenreader
- You can click the label to focus on the field which is great for people with motor issues
- Placeholder text isn't automatically translated by browsers; the label is.

Do we need to keep the pre-pended "Your" on the fields? i.e. "Your email address", "Your password", "Your name" etc.  My personal opinion is that I think it makes it harder to scan for the words you are used to like "Password" and "Email" but you know your clients better than I do!

I've not actually tested the functionality of this yet - I've just updated the visuals although I'm pretty sure it will work.

### CODE REVIEW

**Comment by edwh** [comment]
Happy with this style for the good reasons you give.

The reason I have "Your" is because I find "Email address" quite cold 
and unwelcoming, like something barked at you by an East German border 
guard.  So I'd prefer to keep that unless you can think of some other 
way of making the modal feel friendly.

------ Original Message ------

**Comment by JayyajGH** [comment]
OK cool.  I'll give it a test and submit the PR.  So many hugely popular sites still do this so badly.  Probably not for much longer if Dominos lose the "Domino's v Robles" accessibility case though!

Yeah I can see what you mean.  My only other comment on the "Your" would be the sites that people use the most like Facebook, Amazon, Instagram, BBC etc. all go for the border guard style.  People are used to it.  I'll go ahead with it as it is for now unless you change your mind!  Maybe we could put a kitten on it? :-)

**Comment by edwh** [comment]
Kittens.  Of course.  Mock that up?

------ Original Message ------

**Comment by JayyajGH** [comment]
This is one of my favourite image placeholders:

[](https://placekitten.com/)

**Comment by edwh** [comment]
I deduced the existance of and then located this: 
https://vole.wtf/plaiceholder-images/

------ Original Message ------

**Comment by JayyajGH** [comment]
I'm not getting any feedback if I enter invalid login details though.  Is this part of the work that Nick is doing or is this a separate issue?

**Comment by edwh** [comment]
I pushed a fix for that yesterday, I think - have you merged recently?

**Comment by JayyajGH** [comment]
Ah no sorry I haven't merged since yesterday.  Should have merged before submitting the PR....

**Comment by JayyajGH** [comment]
This is now working ok. :-)

**Comment by edwh** [comment]
Good.  Normally I don't have as good an answer to bugs as that...

------ Original Message ------

**Pull request merged**
