### PR TITLE
Add robots file

### PR DESCRIPTION
**Pull request by JayyajGH**
An initial robots file

### CODE REVIEW

**Comment by edwh** [comment]
Assuming you've done the right thing, then that looks correct :-).

**Comment by JayyajGH** [comment]
That's the most basic of robots file that I've used elsewhere.  It basically allows any bot to crawl it.  The main bit is the link to the xml sitemap

**Comment by JayyajGH** [comment]
You can point a tester tool at it once it's live so give me a shout when it is and I'll double check it's ok

**Comment by JayyajGH** [comment]
It is probably worth looking at the website folder to see what is accessible. I've not familiar with exactly what is deployed so probably best for you to do this bit.  I've set "disallow" to be empty which means everything is visible.  You would usually use this section for stopping bots looking at wp-admin folders and similar.

**Comment by edwh** [comment]
Live.  I'll tweak the URL to add www. soon.

------ Original Message ------

**Comment by JayyajGH** [comment]
Ah dang.  I double checked the live url but forgot that chrome removes the www subdomain from it!

**Comment by JayyajGH** [comment]
Just about to create a PR to add the subdomain

**Comment by edwh** [comment]
No need, I did that.

------ Original Message ------

**Pull request merged**
