### PR TITLE
Tidy the three containers

### PR DESCRIPTION
**Pull request by JayyajGH**
More design shrapnel stuff.  Is there any reason the privacy container has a white background and the others don't?

### CODE REVIEW

**Comment by edwh** [comment]
Thanks, I'll have a look later.

Generally for blocks of text we should have a white background as 
they're not very readable on the wallpaper.

------ Original Message ------

**Comment by JayyajGH** [comment]
ok cool.  Yeah give me a shout and I can switch the others to white if required.

**Comment by edwh** [comment]
Please.

Or:

PLEASE!

------ Original Message ------

**Comment by JayyajGH** [comment]
All pages should now have white backgrounds

**Comment by JayyajGH** [comment]
Also removed from the shrapnel issue

**Pull request merged**
