### PR TITLE
#142 improve group header layout to avoid any overlap, obtuse or odd …

### PR DESCRIPTION
**Pull request by aaronferris**
Id highly recommend pulling this down and taking a look before merge because

A) I cant find our discussion history (I seem to recall trying to avoid too much vertical whitespace or a logo too large)
B) This was really fiddly across different break points (IE between lg and xl, also 991/992 as this is when the overall layout changes from 12 columns to 6. 992 to 1199 would be my main concern as there just isnt enough horizontal space to get the 3 elements sitting side by side, hence the buttons sitting underneath, as they do on mobile).

Ive applied what I feel is best, as far as size of each element is concerned but as above, open to feedback at specific breakpoints whether we want a reposition of buttons etc.

### CODE REVIEW

**Comment by edwh** [comment]
Thank you.  This needs a careful look, so I won't rush it.

------ Original Message ------

**Comment by edwh** [comment]
It certainly looks better.

There are still a few niggles.  In this example the Join/Leave button doesn't show because I am a moderator on that group.  But I think the effect is the same.

At around 500 width it looks like this:

image

I think if we could put the "See community events" across the whole width it would save a line break.

At around 600, it looks like this:

image

The image is small and the text squished - I think it would look better as it does at the 500ish display there, where the buttons move onto the next line.

At the widest:

image

I think the contact button is taking up too much space here - the image could be slightly bigger (but it's ok), and if the central section had more space it wouldn't line break.
You get similar effects when you keep growing and the sidebars kick in and shrink the central space.

**Comment by aaronferris** [comment]
We need to be careful that we dont start adding specific breakpoints for various use cases, Bootstrap uses 4 and we should try and stick to these for consistency, I would recommend

Point 1

This is a tricky one, if we look at moving this text it starts to look disconnected from the group description at say 360.

Screenshot 2020-01-19 at 10 14 48

Screenshot 2020-01-19 at 10 15 34

Point 2

I would recommend we position the buttons underneath for all devices < 768 as there isnt enough real estate to handle the buttons top right. Same for 992-1199, same problem.

600
Screenshot 2020-01-19 at 10 58 39

768
Screenshot 2020-01-19 at 10 58 29

This would also be the case for 992-1199
Screenshot 2020-01-19 at 10 59 35

Point 3

This is a tricky one, because we are sticking with bootstrap grids anything less than 5 columns for the text means there isnt enough space for the 'contact volunteer' button at the XL breakpoint (1200)

Screenshot 2020-01-19 at 10 11 33

Ive tried to remedy this by overriding the bootstrap column widths, and the gutters for > 1200. The screenshot in your example is missing the join button which does = more horizontal whitespace.

Screenshot 2020-01-19 at 11 02 27

Screenshot 2020-01-19 at 11 02 34


If this still doesn't resolve and do what we want, a rewrite of this to not use bootstrap grids would be on the cards.

**Comment by edwh** [comment]
Definitely agree with sticking to Bootstrap breakpoints.

On point 1, I think the text would look less disconnected at 360 if the image was larger.  Not sure whether that's feasible, though - the tagline on the right is variable length for different groups.  But I'm ok with it looking as it does in your screenshot.

Point 2 - ok, underneath it goes.

Point 3 - this looks ok.  Wasted whitespace is less of an issue on larger screens, so this looks ok to me.

Ready to merge, then?



The links are causing spaces before commas, which is mildly annoying - might be my IDE formatting.

**Comment by aaronferris** [comment]
So I think we're good with point 2 and 3, so just point 1 needs to be remedied before merge

Ive increased the image size an extra column, doesn't look too bad

Screenshot 2020-01-19 at 11 19 53 (2)
Screenshot 2020-01-19 at 11 19 57

Re: the commas, that's because they exist outside of the link creation, we could include them as part of the link text instead. I dont confess to be an SEO expert but I think we're safe including punctuation in link text, providing it doesn't form part of the URL to cause any crawler confusion.

`      Founded {{ group.founded | dateonly }}. {{ group.membercount.toLocaleString() }} current freeglers.
          <br>
          See
          <nuxt-link :to="{ path: '/communityevents/' + group.id }">
            community events
          </nuxt-link>,
          <nuxt-link :to="{ path: '/volunteerings/' + group.id }">
            volunteer opportunities
          </nuxt-link>,
          <nuxt-link :to="{ path: '/stories/' + group.id }">
            stories
          </nuxt-link>, or
          <nuxt-link :to="{ path: '/stats/' + group.nameshort }">
            stats
          </nuxt-link>`

I would assume its just a case of including them as part of the link text as so

**Comment by edwh** [comment]
Ok, I'll merge as is.

I kind of get irked by the comma being coloured as part of the link, 
though.  But there are more important things just now...

------ Original Message ------

**Comment by edwh** [comment]
Merged.  Thanks for fiddling with this.  It's much better now.

**Pull request merged**
