### PR TITLE
Fix the issue with deleting dates

### PR DESCRIPTION
**Pull request by JayyajGH**
I tested this before I refactored the startenddate component and the issue was still there.  It looks like the array is correct but the display is doing something weird and not updating correctly.

### CODE REVIEW

**Comment by edwh** [comment]
Maybe try replacing the splice with:

`this.$delete(this.editableDates, index)`

**Comment by JayyajGH** [comment]
The splice is working ok.  The data in the component is ok after the delete too.  Looks like the date-picker component isn`t updating it`s display.

**Comment by JayyajGH** [comment]
Hmmm.  What is the startd stuff all about?  Looks like that isn`t being updated.  The start prop is updated but the startd data isn`t

**Comment by edwh** [comment]
That's usually a reactivity issue, which can be caused by how the data 
is set.

Anyway, leave the TODO on there and I'll have a look at some point.

------ Original Message ------

**Comment by edwh** [comment]
I think that's to avoid mutating the props.  Perhaps the change() method 
needs to set startd/endd.

------ Original Message ------

**Comment by JayyajGH** [comment]
The delete button removes the date from the editable dates collection. The display fields (date-picker) get there data from the startd and endd data values which only seem to be updated on mount.

**Comment by JayyajGH** [comment]
Startd and endd are already set by the component.  The start and end props are used to set up startd and endd on mount.  I`m thinking the only way to make the internal data values change is to set them from a computed property or a watch.  I`ll have a think...

**Comment by edwh** [comment]
I'll have a look when I finish the chunk I'm doing.

------ Original Message ------

**Comment by JayyajGH** [comment]
I hate being stumped by stuff...  Thinking this through you need to update the local data value when the prop changes.  The only way I can think of doing that is with a watcher.

e.g.
`
watch: {
   start: function() {
      this.startd = this.start
    }
}
`

This seems to work correctly.  I`ll update the  PR for you to have a look at when you`re next free...

**Comment by edwh** [comment]
But what is it that is changing the values?

**Comment by JayyajGH** [comment]
If you click delete then it raises an event to the parent component - StartEndCollection - that deletes the entry from the array (with splice).  The prop is then updated in the StartEndDate component but the startd and endd are only updated on the mounted event, not when the props change.

**Pull request closed without merging**
