### PR TITLE
Add form validation

### PR DESCRIPTION
**Pull request by nicksellen**
So, the idea for this is to use vuelidate, I'm already familiar with it, and it's the first suggestion given on the [boostrap-vue validation page](https://bootstrap-vue.js.org/docs/reference/validation/#form-validation) too.

One of the things that it doesn't do for you is the error message handling, leaving that to you - which is a reasonable idea as there are many ways to show/display/fetch the actual error messages. The downside is it can get quite verbose and repetitive. So, I thought to create new form components that wrap the bootstrap ones to take the tedium out of it.

It basically passes everything through to the underlying component, apart from the props `validation` (the vuelidate object representing a specific field) and `validation-messages` (a map of validation type -> message) which it uses itself.

I used the same pattern as shown in the bootstrap-vue docs, so it looks a bit like this:

validation

How do you feel about this general approach (wrapping the bootstrap form components)?

The other question that quickly arises is what the validation rules actually be? I wonder if there is a reference somewhere I can follow? (maybe the backend has some hints? or the old frontend?).

### CODE REVIEW

**Comment by edwh** [comment]
Happy with this general approach, as long as there is some way to result 
in an overall check for the whole form.  It looks like you have that in 
the example for when you click - I don't quite follow how it works, but 
I can pick that up later - but can you also do it dynamically, e.g. to 
enable/disable a button once the inputs become valid/invalid?

The error messages need to be nice and warm, e.g. "Please add a title" 
is nicer than "Title is required".

There's no real documentation of the validation required.  You could 
look in the old code, and there are some notes in some of the todos.  
It's probably easiest to do what seems obvious and I'll review it - once 
you've put the mechanism in place it'll be easy to add rules.

------ Original Message ------

**Comment by nicksellen** [comment]
> Happy with this general approach, as long as there is some way to result in an overall check for the whole form.  It looks like you have that in the example for when you click - I don't quite follow how it works, but I can pick that up later - but can you also do it dynamically, e.g. to enable/disable a button once the inputs become valid/invalid?

Yup, you can really do it any way desired with this stuff, it's all manually triggered - in this case I've hooked into the _blur_ events on the fields to trigger validation on those specific fields (e.g. `$v.event.title.$touch`), and the `saveIt` method triggers all the fields with `$v.event.$touch`). It also keeps track of which fields are _dirty_ (changed).

Although if the button is disabled until everything is valid, it's not clear how to trigger validations for fields which you haven't touched yet, and pre-emptively touching them all makes the whole thing go red and scary, so I think keeping the button enabled might be better.

But it could work with a disabled the button if it's very clear which fields are required, so the user is likely to touch them all before wanting to attempt a save.

Maybe a bit of UX research would come up with a good approach...

> There's no real documentation of the validation required.  You could look in the old code, and there are some notes in some of the todos. It's probably easiest to do what seems obvious and I'll review it - once you've put the mechanism in place it'll be easy to add rules.

Ok, I'll probably keep it minimal in that case, and see about getting this community event form mergable. Then I can proceed to the basic stuff to other forms, and maybe you can add in various rules. I suspect there will be some more fiddly ones though... e.g. `StartEndCollection` - I guess for community event there should be at least 1 date pair, and each should have a start and end? ... I'd also prevent adding in end dates earlier than start dates, shouldn't wait for validation to catch that.

**Comment by edwh** [comment]
There may be a standard way to indicate mandatory/optional stuff nowadays, though I've seen so many variations that I doubt it.

Probably keeping enabled is OK, but Google a bit.

Yes, events have at least one date, end after start, gap between not too long. Thing there may be a TODO about that.

I had some code to change the end date when you set the start date to ensure it was always after. That had issues though and would need doing carefully. That aspect can wait.

**Comment by JayyajGH** [comment]
My first thought was is it getting a bit like a rabbit hole with components wrapping bootstrap components wrapping HTML elements?  It's probably best to ignore that opinion though as I'm not a big fan of bootstrap (have I mentioned that before? :-p)

My preference for validation is to always have the "Continue/Submit" button enabled rather than disabling it until all fields are valid/entered.  There is nothing worse than not being able to see what you have missed.  This tends to create a much more accessible experience too.  This also fits in with how Nick was suggesting it would work technically.

I've got a bunch of docs saved somewhere on the topic of validation/forms.  I'll try and dig some out...

**Comment by JayyajGH** [comment]
Adam silver is a well respected form designer. This link has loads of great info:
https://adamsilver.io/articles/form-design-from-zero-to-hero-all-in-one-blog-post/?ref=heydesigner

Some of that is also backed up here:
https://uxmovement.com/forms/why-users-make-more-errors-with-instant-inline-validation/

**Comment by edwh** [comment]
Interesting stats on instant validation in the second link.

------ Original Message ------

**Comment by JayyajGH** [comment]
This is obviously the internet so everything has to be taken with a pinch of salt.  Adam Silver stuff is usually pretty well backed up and referenced though so I do tend to trust what he says.

**Comment by JayyajGH** [comment]
> I had some code to change the end date when you set the start date to ensure it was always after. That had issues though and would need doing carefully. That aspect can wait.

I think this needs to be thought about carefully.  Changing something automatically that the user has entered could be confusing.  e.g. someone sets up an event for a few weekends time - 21/12 - 22-12.  They then realise they meant the weekend before so want to change the 22nd to 15th.  And then before they can change 21st to 14th  the date they have just changed automatically updates to something else.

**Comment by edwh** [comment]
Yes, it needs to be careful and is a separate PR from this initial 
validation.  I think probably we shouldn't change the end date once they 
have set an end date, but I think it's helpful to change the end date 
when they first change the start date.

It helps a lot with events which are on the same day (which is the vast 
majority) because it avoids having to do the tedious month and date 
selection twice, leaving you to just focus on the time.

------ Original Message ------

**Comment by JayyajGH** [comment]
> but I think it's helpful to change the end date
> when they first change the start date.

Yeah absolutely.  My form hatred is when you set a start date and the end date stays at the current date.  ARGH!

**Comment by nicksellen** [comment]
> My first thought was is it getting a bit like a rabbit hole with components wrapping bootstrap components wrapping HTML elements? It's probably best to ignore that opinion though as I'm not a big fan of bootstrap (have I mentioned that before? :-p)

I think you just described programming... :) It's one big rabbit hole. And it doesn't stop at the HTML element either... if we weren't using bootstrap we'd be using either another UI framework with it's own components, or writing our own reusable components, so it's not much different in any case. 

This approach to wrap components is the standard vue approach: _Note that in Vue 2.0, the primary form of code reuse and abstraction is components_ (on https://vuejs.org/v2/guide/custom-directive.html - as I was wondering whether a directive could do the same thing as this component).

The idea is that each component is doing one thing, and if you are not thinking about that particular aspect at one moment, you don't need to open up that component - so long as you trust it does what it promises to do.

The opposite, putting everything directly in the lower down component means it would be very verbose and a lot of duplication of code. Maybe thinking of components like functions helps? (if you had the same code in a few places, you'd abstract it into a function, which is also a "rabbit hole" of functions, I like rabbit holes anyway, I think Alice had a much more interesting time after choosing that option).

Also, thanks for form thoughts, that's exactly the kind of thinking I was hoping you might have :)

I'm wondering how to make it concrete - to implement Adam Silvers ideas we'd have to implement a lot of our own components, which we could do, but it would be quite a lot of work. On the other end of the scale we could just hold off validation until the user first presses the submit button (the suggestion from the other article), but keep using all the bootstrap components as already exist.

Thoughts?

**Comment by JayyajGH** [comment]
Ha!  Yeah good point!  I think as you say, the main thing is to keep things DRY.  And if that means creating more components then that is what is required.  I don't particularly like all the layers but I dislike duplication more.

It sounds like the second suggestion would be the best place to start.  I think his main point on validation is don't interrupt the user when they are "in the flow" of completing the form and don't disable the "continue/submit" button.  These are the points that I've seen mentioned in lots of different places.  The other stuff might be considered more of a personal opinion and would seem to be less important.

There are still a few things I would like to do with the forms but is outside of this discussion e.g. remove placeholders, set up the forms semantically etc.

**Comment by edwh** [comment]
Hold off until first submit and keep the components as they are.

The other stuff in the article is quite interesting and would be worth 
looking at further, but I can see us getting a bit bogged down in it.

------ Original Message ------

**Comment by JayyajGH** [comment]
> The other stuff in the article is quite interesting and would be worth
> looking at further, but I can see us getting a bit bogged down in it.

Indeed.  It would be great to make it all 100% perfect but it would never get finished that way.

**Comment by nicksellen** [comment]
Thanks for the input, that's clear for me on how to proceed :)

**Comment by nicksellen** [comment]
Ok, some progress :)

- I went with the behaviour to hold back on validation until they first press submit
- if there are errors we jump up to the first error
- I put things in a [`<b-form-group>`](https://bootstrap-vue.js.org/docs/components/form-group) so it also colours the label
- I made some attempt to handle resetting the form better - not sure what is best here, if you click outside the modal it closes, but I leave all the state as it is, if you click _Cancel_ it will reset the event and the data to initial values, doesn't seem perfect to me, but maybe enough for now
- have not tried editing existing events yet, as to try it I have to create an event and get it approved (annoying cycle when developing! would like a better dev environment to solve that)
- I managed to put validation around the group select and the start end collection without actually touching those components... (although visually the group select does not get coloured like the other input fields, but that's ok for now)

Here's a screenshot showing all fields with an error:

allerrors

Comments?

**Comment by edwh** [comment]
Coming along nicely.  A couple of thoughts:

- I would be inclined to move the validation for start/end dates inside that component, with props to control behaviour if you need it.  It's that component's responsibility, I think, and otherwise you'll have to duplicate logic if we ever use that component elsewhere.
- Could you move any more code inside the mixin?  For example the focus on first error and the touch that you do on the submit looks like it would be fairly common code wherever we did this.
- @JayyajGH might have a view on whether, for accessibility reasons, we should include a b-alert when validation fails as well as highlighting the errors.

**Comment by JayyajGH** [comment]
I think at the very least there needs to be something with a role="alert" to inform the user that something on the page has changed.  I think this is why the accessibility experts like the idea of displaying a list of all the errors on the page at the top of the screen.  It gives something to hook the alert role on to and takes the user back to the top of the page. Maybe even just a "There has been an error submitting your form.  Please resolve all the issues blah blah blah" message with a role of alert.

**Comment by JayyajGH** [comment]
I saw somewhere recently that everyone should try and buy at least one Christmas present using a screenreader. I'm not sure I have that amount of free time!

**Comment by nicksellen** [comment]
> I would be inclined to move the validation for start/end dates inside that component, with props to control behaviour if you need it. It's that component's responsibility, I think, and otherwise you'll have to duplicate logic if we ever use that component elsewhere.

In this case the validation of the dates is the responsibility of the community event (e.g. you need at least one), whereas for the volunteer things you can have none, but they still use the same component.

Also, I don't think vuelidate works if you try and have multiple nested components with independent validation (it needs to be on the main `$v` object, but the data can be arbitrarily deeply nested).

> Could you move any more code inside the mixin? For example the focus on first error and the touch that you do on the submit looks like it would be fairly common code wherever we did this.

It would be to create another mixin actually, the one on the CommunityEventModal is just the regular vuelidate one, and the one I created is just for the specific form components. I might make one that includes the vuelidate one, plus our extensions (like focus first error...). Seems a reasonable approach.

**Comment by nicksellen** [comment]
This is the (slightly clean up) HTML that comes out of the bootstrap component when there is an error on an input field:

```
<div role="group" class="form-group is-invalid" aria-invalid="true">
    <label for="title" class="d-block" >What's the event's name?</label>
    <div>
        <div id="title" type="text" placeholder="Give the event a short title">
            <input id="title" type="text" placeholder="Give the event a short title" class="form-control is-invalid" aria-describedby="title-feedback" maxlength="80" aria-invalid="true">
            <div id="title-feedback" class="invalid-feedback"><span>Please add a title</span></div>
        </div>
    </div>
</div>
```

Is that enough `aria`? Or maybe adding the `role="alert"` to the error message?

**Comment by JayyajGH** [comment]
Does vuelidate add an "aria-invalid".  Ha! You've just answered that question!  That's good.

Webaim have some good stuff to say about form validation.  Much of it we have already discussed though.
https://webaim.org/techniques/formvalidation/

**Comment by JayyajGH** [comment]
I don't think you need to give every message a role=alert.  I think it tends to be just the main error.  In an ideal world that would be the list of all errors at the top of the page.

**Comment by nicksellen** [comment]
That article says: _This error message should be visible, informative, and accessed directly. One method is to use a JavaScript alert box_ - I can't take it seriously after that :sob: 

Is it really better to put errors at the top in a list? I would hope `aria-invalid` somehow lets the user navigate between them? Errors at the top to me, _as well as_ inline with the fields seems kind of overkill... 

Btw the `aria-invalid` is from bootstrap, not vuelidate. Vuelidate does nothing regarding presentation, no components, html, error messages or anything, it only concerns itself with the logic of validation (to keep it flexible to use with whatever components you want).

**Comment by JayyajGH** [comment]
Ha!  Everyone loves a javascript alert box!  Listing them all at the top does appear to be the solution listed on many different websites.

I would suggest that as long as the user is alerted to the error in some way (e.g. role=alert somewhere) and each field has an error state (e.g. aria-invalid) then that should be enough.
I've not got much experience with accessible validation so I am guessing a bit here.

**Comment by nicksellen** [comment]
Ok, _maybe_ this is mergeable now.

A significant change I made after using it for _editing_ events, is to clone the incoming `event` prop into `eventEdit` data field. Otherwise we end up mutating the contents of the `event` prop, and the listing of the event gets updated as we type.... Actually, I like this editing model in general, as it lets us keep the original event around for comparing to (e.g. the `olddates`...) logic.

Also, I moved the logic to focus the first error field into a mixin.

There are a couple more TODOs in there, but maybe useful to have the validation in the main code?

I might have a few days before I can do more on this again (Monday+ probably). Happy if you want to leave it to after then to merge too :)

**Comment by edwh** [comment]
Thanks.

I think it's mergeable as is so I'll do that this evening to get it in.

Minor comments for when you get back to it:
Will placeholder work?  You don't list it as a prop for your new 
input/textarea components.  Ditto minlength, spellcheck, probably 
others.  Unless you've done something fancy to inherit all of them which 
I can't spot because the guy next to me has his headphones on too 
loud."It's id" should be "Its id" (sorry).  "detirmined" => 
"determined"Do we really need a separate red colour?  We have too many 
colours so I would be inclined to make color-red and color-danger the 
same.There is obviously more validation to do on events.  Start/end 
dates (end after start, no event longer than 4 days), sensible min 
length on required fields, email syntax.  But you know this :-).Would be 
nice to have some more comments on the vuelidate stuff for those like me 
who aren't familiar with it, e.g. touch, dirty, anything on $v.The 
nextTick stuff looks deeply hokey and fragile - exactly the kind of 
thing I'd write and then feel it meant I wasn't using Vue properly.  If 
we really have to do this then I'd think a 1 second timer might be more 
robust.Some nice code-level tidyups in here, thanks.  I've not seen 
const { id } =this.event before; presumably that resolves to undefined 
if the property isn't present.  Personally I prefer to explicitly set 
things to null when I know they are absent and tend to reserve undefined 
for bugs, but that's personal preference.

------ Original Message ------

**Comment by nicksellen** [comment]
> Will placeholder work?  You don't list it as a prop for your new input/textarea components.  Ditto minlength, spellcheck, probably others.  Unless you've done something fancy to inherit all of them which I can't spot because the guy next to me has his headphones on too
loud.

Yup, there is something "fancy", the pattern is called "higher order component" (basically, one that wraps another one, in a more-or-less transparent way), and in vue you can do `v-bind="$attrs"` to pass down everything that wasn't declared as a prop (so the attrs on the component are a mix of props and attrs really). See https://vuejs.org/v2/api/#vm-attrs for a bit more detail.

The downside is worse auto-completion for IDEs :/

> Do we really need a separate red colour?  We have too many colours so I would be inclined to make color-red and color-danger the same.

I didn't add a seperate colour, just stole the definition from the bootstrap colours, but currently they are not imported/combined with `color-vars`. So, I had to re-declare it. bootstrap danger is the same as bootstrap red anyway. Would be nice to have access to bootstrap vars inside the custom freegle vars, but seems out of scope for this PR, maybe @JayyajGH has a thought on that?

> Start/end dates (end after start, no event longer than 4 days), sensible min length on required fields, email syntax.  But you know this :-).

Yup, was gunna wait until the work done to set end depending on start was done, as it is kind of related/interleaved. I think it shouldn't be needed to validate on that as the component will already ensure that is valid. But yes, for "event length", I'll add a TODO.

> "It's id" should be "Its id" (sorry).  "detirmined" => "determined"

Will fix :)

> Would be nice to have some more comments on the vuelidate stuff for those like me who aren't familiar with it, e.g. touch, dirty, anything on $v.

I would just refer you to the vuelidate docs ---> https://vuelidate.js.org/#sub-v-values

> The nextTick stuff looks deeply hokey and fragile - exactly the kind of thing I'd write and then feel it meant I wasn't using Vue properly.

Agree, it's a hack really. Ideally you don't need to think about which elements to trigger focus on, I think there should be a better way, but couldn't come up with something yet. Could set refs for each field and trigger focus like that - then don't need to rely on the bootstrap classes being set for referencing them. I think that should work. Another TODO!

I think it's reasonably deterministic though, I think there are a number of things that get triggered to re-render, i.e. 3 ticks never works, 4 ticks always works (within the confines of my playing around).

> I've not seen const { id } =this.event before; presumably that resolves to undefined if the property isn't present.  Personally I prefer to explicitly set things to null when I know they are absent and tend to reserve undefined for bugs, but that's personal preference.

The property is (aka should be) always present as we set `id: null` in `initialEvent`, but yes it would resolve to `undefined` if it wasn't present. But by creating a null valued property by default we allow the reactivity to watch it when/if it gets set to something.

**Comment by JayyajGH** [comment]
> Would be nice to have access to bootstrap vars inside the custom freegle vars, but seems out of scope for this PR, maybe @JayyajGH has a thought on that?

Not entirely sure what you mean here?  Do you just mean you want to access the bootstrap variables?  I've done something similar somewhere here using:
`@import 'node_modules/bootstrap/scss/variables';`

To make something clear, I'm not a big fan of what I've done with the colour variables.  Ideally we would use css custom properties but to make that work in IE would need a polyfill/ponyfill and I've not used any before so that needs looking into.  At least we now have a common place to define the brand colours and it exposes how many there are which means we can start consolidating them.  Once we moved to custom properties it will then be easy to switch the current definitions over.  Consolidating the colours will mean checking where each one is used and on which colour background to check the contrasts are AA compliant before we remove some.

**Comment by nicksellen** [comment]
OK, I switched to a ref-based approach for focusing the first error. More proper, but also needs more fields to be set (namely, the ref field), could consider abstracting that away too in the future...

**Comment by nicksellen** [comment]
@JayyajGH more concretely, when using the bootstrap `:state` prop on form components it puts a nice red/green border and label depending on validation status.

In `CommunityEventModal` though the label colour is set to `$color-green--darker` which override the nice red from bootstrap. I wanted to keep the green for normal case, but make it the same as the border for error cases, but `_color-vars.scss` does not include the bootstrap colours, so I didn't have those available. I didn't really want to pull in all the bootstrap vars, as it seemed having our own color vars is useful.

Actually I didn't even want to touch any of that... 

I thought to switch to importing bootstrap vars, but it gives me this big fat error:



```
SassError: argument `$color` of `darken($color, $amount)` must be a color
        on line 174 of node_modules/bootstrap/scss/_variables.scss, in function `darken`
        from line 174 of node_modules/bootstrap/scss/_variables.scss
        from line 315 of /code/freegle/iznik-nuxt/components/CommunityEventModal.vue
>> $link-hover-color:                        darken($link-color, 15%) !default;
   ------------------------------------------^
```

... even though the import is used elsewhere (fyi, you can use `@import '~bootstrap/scss/variables';` so don't have to have the ugly `node_modules` bit there).

**Comment by nicksellen** [comment]
... aha I had to import bootstrap functions too :)

**Comment by JayyajGH** [comment]
Yeah I made that mistake too!  Generally I like the idea of colours being defined in one place.  That way you get a consistent look and feel across the whole site.  I don't mind where those colours are defined but I think there needs to be a place to go that lists them all.  I think going forward it would be good to have all freegle colours listed in the same place and not define extra colours outside of that.  I think maybe stuff used from bootstrap needs to be dealt with separately. It might just be the case of adding a comment in the colour definition file maybe.  I'll have a think...

Ah yes "~". Is it nuxt that defines that alias?

**Comment by nicksellen** [comment]
> Ah yes "~". Is it nuxt that defines that alias?

According to https://github.com/webpack-contrib/sass-loader#resolving-import-at-rules it tells webpack not to treat it as a relative import, which makes it look in node_modules... most importantly it's different to `~/someLibrary` in js files (which means relative to the project root).

**Pull request merged**
