### PR TITLE
Move the local storage checks into a component

### PR DESCRIPTION
**Pull request by JayyajGH**
Move the local storage functionality into a component to start to tidy up the default layout

### CODE REVIEW

**Comment by edwh** [comment]
Thanks.  There's a lot to tidy up in there, I'm afraid.

There's a bug in this code - I see the warning when I don't believe it.  Possibly something to do with multiple tabs being open.

**Comment by JayyajGH** [comment]
I'm guessing by the fact that you merged it, you meant the bug is an existing bug rather than something I have introduced?

Most of the file appears to be the navbar.  I've tried a few ways of tidying it but had some issues so I need to think of another angle I think!

**Comment by edwh** [comment]
Yes, the bug is existing and so far undiagnosed.

Maybe see if you can combine the small and large navbar first? Not sure whether that will work but it would be an alternative approach.

**Comment by JayyajGH** [comment]
Yeah that was one of my first thoughts too.  There are so many different parts to the navbar are in different orders etc. that it's not the easiest of refactors.  I'll have a play...

**Pull request merged**
