### PR TITLE
Uncapitalise the text as it is read out strangely

### PR DESCRIPTION
**Pull request by JayyajGH**
When written in caps a sr reads out OFFER and WANTED as the individual letters.

### CODE REVIEW

**Comment by edwh** [comment]
I don't want to do this - we want them as OFFER and WANTED for existing users.  So does that mean we need to use sr-only etc?

**Comment by JayyajGH** [comment]
This is just screen reader only so won't be displayed anywhere

**Comment by JayyajGH** [comment]
<h2 class="sr-only">
          List of wanteds and offers
        </h2>

**Comment by edwh** [comment]
Doh.

**Comment by JayyajGH** [comment]
This is part of the testing I'm doing on the new message stuff.

**Pull request merged**
