### PR TITLE
Convert A mailto into ExternalLink so they work in ios app

### PR DESCRIPTION
**Pull request by chriscant**
Updated a load of A mailto links to use ExternalLink so they work in iOS app

### CODE REVIEW

**Comment by edwh** [comment]
Before I review in detail, I notice that in e.g. CommunityEventModal the change will result in whitespace inside the <a>.  I have cruelly forced you to avoid that in an earlier fix.  Can you do so in this?

Slightly more generally, I wonder whether for ExternalLink we should use a prop rather than a slot?  That would allow us to handle the spacing issue inside that component.

**Comment by chriscant** [comment]
Ah yes, 
My editor automatically formatted it, which caused the probem.
I'll check the whitespace now, and make a note about converting to a prop.

**Comment by edwh** [comment]
Thanks.  Apologies in advance for when I forget to use it.  I really need to sort out some project lint rules to flag up stuff like this.

**Comment by chriscant** [comment]
Thanks. There was one mailto on a button which I didn't do - to check our iOS app testers

**Pull request merged**
