### PR TITLE
Refactor the common parts from the sidebar items

### PR DESCRIPTION
**Pull request by JayyajGH**
So I've pulled out the duplicate code in these two components.  I don't think the thing you mentioned on the other PR is relevant here as the separate modals handle that.
The only thing I'm not happy with here yet is the name of the component and the names of some of the props.  Basically I need a name for something that can be an event or an opportunity.  Any ideas?

### CODE REVIEW

**Comment by edwh** [comment]
"CommunityFeature"?

------ Original Message ------

**Comment by JayyajGH** [comment]
It's not giving me one of those "that's it" moment but it's better than what I had.  We can always change it later if we think of something better.

**Comment by edwh** [comment]
It's that or AbstractActivityOrLocationBasedThingummy.

------ Original Message ------

**Comment by JayyajGH** [comment]
Perfect.  You've hit the nail on the head with that one. :-)

**Comment by JayyajGH** [comment]
We regularly have the conversation at work that naming stuff is the hardest thing about development.

**Comment by edwh** [comment]
Yeah.  That and my thumb.

------ Original Message ------

**Comment by JayyajGH** [comment]
Is the key used when displaying the volunteer ops/community events important?  At the moment one uses "key-<id>" and the other uses "volunteering-<id>" .  Can it be changed to something like "item-<id>"?

**Comment by edwh** [comment]
I think the key needs to be unique on the page otherwise Vue complains.  
So they need to be different otherwise if they are both displayed on 
sidebars it might clash if the ids happen to be the same.

"key-" is a terrible choice of key, though.  As long as it is unique 
across both types, "item-id-type" or something would be fine.

------ Original Message ------

**Comment by JayyajGH** [comment]
One doesn't use key - my mistake.  It is "event-" and "volunteerings-"

**Comment by JayyajGH** [comment]
OK so the ID's ca n potentially be the same.  In that case I'll make them different

**Comment by JayyajGH** [comment]
OK I've made some tweaks to naming now.  It's not the prettiest of components but it has at least removed the code duplication for the two sidebar items.

**Comment by JayyajGH** [comment]
I don't have any community events.  Do you have any that you can check this bit works too?

**Comment by JayyajGH** [comment]
Comment moved from another issue:

Sorry, I know you asked me explicitly about this, but reviewing the code I think the title should probably be clickable too, as I can definitely imagine people doing that to find out more.

**Comment by JayyajGH** [comment]
Comment moved from other issue:

I underuse :is, I think, so it's nice to see that. It's a little bit undermined by the if statement with explicit reference to the value of featureComponent. Should we pass in a prop which we used to set the key value?

If it would help we could change VolunteerOpportunity and CommunityEvent to take the same prop name, e.g. item.

**Comment by JayyajGH** [comment]
The title is now clickable

**Comment by JayyajGH** [comment]
With reference to your comment around "is".  This is the bit I was referring to when I said it wasn't pretty.  I didn't want to change the prop on each component hence why I used the if statement.  But yeah I agree it would be nicer.
I'll change the components to use the same prop and pass in the key.

**Comment by edwh** [comment]
I think you need to check for other uses of CommunityEvent and VolunteerOpportunity, and change to use the item prop in there?

**Comment by JayyajGH** [comment]
Argh.  I think working on two changes in exactly the same area has confused me.  I've also got conflicts with my other change now so I'll sort.

**Comment by JayyajGH** [comment]
That issue should now be resolved.  I've tested the regular places the VolunteerOp component is used.  Would you be able to test the communityevent component and the mod tools?

**Comment by edwh** [comment]
Yes, I'll test those two now.

------ Original Message ------

**Comment by edwh** [comment]
Worth testing as I found a bug in a recent fix I made.  Merged.  Thanks for tidying this up significantly.

**Pull request merged**
