### PR TITLE
Feature/map animation

### PR DESCRIPTION
**Pull request by JayyajGH**
Re. visualise map animation stuff discussion on slack....

How about something like this?  A bit of fade in and a bit of bounce.  Excuse the coding as this is just knocked up for a demo.  Just checking if this is the sort of thing you are after

### CODE REVIEW

**Comment by edwh** [comment]
This is the kind of thing, yes.  Suggestions - doesn't mean you need to 
do them all, just food for thought:
More bounce than squish - not sure that works well with people's faces.
In the version I had ages ago it dropped in from the top, fading in as 
it arrived, then bounced, a bit higher than yours.  That was all horrid 
JS.
Probably a bit bouncier when it first appears.  Maybe a bit faster so 
that it feels more of a sense of excitement than resting pulse?
Ideally not all bouncing at the same.
Maybe a shrink and fade for the removal.
Similarly some stuff on the photo and textboxes, but probably just 
expanding and fading in, and a speech arrow thingy.

But yes, exactly along these lines.  You could spend forever on it, and 
that'd be daft.

------ Original Message ------

**Comment by JayyajGH** [comment]
I'll have a play with some tweaks.  Yeah good point re. the squished faces.  It just felt a bit dead with just bounce so I tried to liven it up a bit.  I'll try what you did originally then and see how that looks.  Not having them all doing the same thing at once might be trickier with this solution.  I guess we could use first-of or whatever the CSS properties are called. Watch this space...

**Comment by edwh** [comment]
We can always delay the add in JS.

**Comment by JayyajGH** [comment]
Yeah true.  I'll try out some different animations first to get something working.  Got a meeting for the rest of the morning so it might be this afternoon...

**Comment by edwh** [comment]
That's ok, out most of the day.

------ Original Message ------

**Comment by JayyajGH** [comment]
A quick tweak before I had off for the morning...

**Comment by JayyajGH** [comment]
Something else we need to be aware of here is the prefers-reduced-motion option.  The rapid moving of the map could definitely cause people issues.

**Comment by edwh** [comment]
That option is new to me. Thanks. 

Probably we would use that option on the landing page to hide the whole of the map. The existing video (which will be below the map) would move up. That would basically then appear the same as currently. 

So I think you can ignore that within the map work.

**Comment by JayyajGH** [comment]
Yeah probably the best idea just not to show it.  It doesn't really work without movement!

**Comment by JayyajGH** [comment]
I've made some tweaks to the bouncyness of the user icon.  See what you think...

**Comment by edwh** [comment]
Yes, that bounciness is nice now.

------ Original Message ------

**Comment by JayyajGH** [comment]
A phrase you don't see very often on a PR

**Comment by edwh** [comment]
True.  I googled to check, but sadly no exact matches.

https://github.com/eBay/NMessenger/issues/19

------ Original Message ------

**Comment by JayyajGH** [comment]
I'll look at the item image next. Might need to tweak some class names as I subsequently realised that VisualiseUser is also used for the item. 
I think we need to be careful were don't go too far here and have stuff bouncing everywhere. I'll try and do something subtle to the image maybe.

**Comment by edwh** [comment]
User fade, too?

The users are the thing to make most bouncy, because that's where the 
enthusiasm should reside.  The image and speech bubbles just need a bit 
of something, so they don't flick into existence and out again in a 
slightly abrupt way.

------ Original Message ------

**Comment by JayyajGH** [comment]
Yeah maybe a slight fade-in would help.  I'll try out some numbers.  In the office today though.

**Comment by JayyajGH** [comment]
@edwh I've now added a slight fade-in to the item image.  See what you think...

**Comment by edwh** [comment]
That's good on the bounciness and image, thank you.

The speech could do with having the arrow thing to make it look like a 
bubble coming out of the icon, and also having some transitions 
(exploding in).

Multiple responses should be offset by a bit to stop them being 
simultaneous, but I can do that in JS later.

------ Original Message ------

**Comment by JayyajGH** [comment]
Speech bubble added...

**Comment by JayyajGH** [comment]
And a bit of a fade-in of the speech bubble.

**Comment by JayyajGH** [comment]
With a lot of stuff on the screen and moving around I'm trying to keep any animations quite subtle.

**Comment by JayyajGH** [comment]
Just found a slight issue.  I'd only fixed one side of the conversation.  I've now done the other but not really tested it fully.  Up to you whether you want to test it or leave it until I get back.

**Pull request merged**
