### PR TITLE
Feature/chat html tidy

### PR DESCRIPTION
**Pull request by JayyajGH**
OK this is the refactor of the chat message box to remove the duplicated HTML and to make it accessible by adding a label.  Do you want to take a look and see what you think?  I've so far only tested it on Chrome on W10.  I'll give it a test tomorrow on other devices.

I currently can't test the alt-shift combination as on Windows 10 it appears to be the key combination to change language.  There wasn't an obvious way of switching this off but I'll investigate further.

### CODE REVIEW

**Comment by JayyajGH** [comment]
I've now tested this on the following:
Chrome on W10
IE11 on W10
Chrome on Galaxy S9
Chrome on Galaxy S20
Safari 12 on iPhone 8.
Safari 13.1 on Catalina

Is there anywhere else that would be useful to test?  I'm struggling to get many of the iPhones working at all.

**Comment by edwh** [comment]
Sounds ok, but what's happening with the iPhones?

**Comment by JayyajGH** [comment]
I'm getting the website loading but just doing the spinny loading/stuck here thing which never goes away and the sign in button never appears.

**Comment by edwh** [comment]
Console error?

------ Original Message ------

**Comment by JayyajGH** [comment]
Nothing.... A few of the ones I managed to test did it to but after refreshing about 30 times it did load in the end.  Others I couldn't get to load.

**Comment by edwh** [comment]
I'm scared of the way you've done it :-).

You've got a handler attached for a null event as a way of avoiding having two DOM elements.  That's the kind of unusual thing that might break on some platforms, he said nervously.  Then again, https://vuejs.org/v2/guide/syntax.html#Dynamic-Arguments seems to suggest that null is an accepted way to remove a binding.

I think the code would be easier to read, and less weird, if you had two div wrappers with a label in each.  Am I missing something?

**Comment by JayyajGH** [comment]
Yeah I did that because of that exact link that you saw too!  This is Vue logic I suppose rather than anything to do with Javascript or the browser so devices/browsers shouldn't matter.  Vue should just not attach a handler to the event in the case it returns null.

The issue with two divs is you then need to duplicate the code.  If you update the classes or logic for one then you also need to update for the other etc.  I guess I just really hate the duplication.

Although I can see where you're coming from.  If you're really not comfortable with it then happy to update it.  I've learnt about dynamic arguments so I've gained from it. :-)

**Comment by edwh** [comment]
I'd prefer it that way.  It feels a bit like code that's too pleased 
with itself for its own good :-).  I prefer a bit of duplication 
sometimes if the alternative is that people have to scratch their heads 
to work out why it is how it is.

...though now I know about the dynamic thing too, which is interesting.

------ Original Message ------

**Comment by JayyajGH** [comment]
Yeah no worries.  I'll park it for now and just add some labels.  In the office tomorrow so it's likely to be monday now

**Pull request closed without merging**
