### PR TITLE
Refactor the top section to use flexbox rather than the bootstrap grid

### PR DESCRIPTION
**Pull request by JayyajGH**
First part of the chitchat page tidy to resolve the width issue.  I thought I would do this in small increments.

Refactor the top section of the page to use bootstrap flexbox rather than the bootstrap grid.  This also resolves the issue with a button contained within an anchor which was creating double button tabbing.

### CODE REVIEW

**Comment by JayyajGH** [comment]
The tooltips that pop up appear to have issues scrolling up sometimes.  Not sure if this is to do with the fixed toolbar.  It works the same way it did before this change but you might want to take a look and add another todo.

**Comment by edwh** [comment]
Which tooltips?

------ Original Message ------

**Comment by JayyajGH** [comment]
The ones that appear if you enter any "find" or "give" type words in the chitchat box.

**Comment by edwh** [comment]
Ah, ok.  Can you get a screenshot of what you mean?

------ Original Message ------

**Comment by JayyajGH** [comment]
capture4

**Comment by JayyajGH** [comment]
I think it only happens if the button is offscreen so it's probably not the end of the world.

**Comment by edwh** [comment]
Ta - pushed a fix for that.

------ Original Message ------

**Comment by JayyajGH** [comment]
Awesome!

**Pull request merged**
