### PR TITLE
Disassociate the semantic headers from the visual aspect

### PR DESCRIPTION
**Pull request by JayyajGH**
A first go at making some of the pages document structure correct.

The browse, volunteer, volunteerings, event and events pages should now have the correct structure.  I've added some headers that are screen reader only so hidden to sighted users.  The bootstrap card already provides the feature to set the element used for the titles and so I've just used that to pass in the heading level.

### CODE REVIEW

**Comment by edwh** [comment]
I'm in the middle of other stuff, and it looks like you're cracking on with this.  Give me a shout when you need it reviewing in case I get distracted.

**Comment by JayyajGH** [comment]
This should now be the bulk of the easy changes.  There are still issues with chats and modal popups etc. but that will be much more complex to resolve so it's probably best to get this set moving as it's an improvement.

**Comment by JayyajGH** [comment]
So just feel free to look at it when you get a spare 5 mins!

**Comment by edwh** [comment]
What's the rationale for underscores and dashes in class names?

For example, you have "community__heading", and "header--size4".  

There's probably single dash, single underscore, camel case elsewhere in the code.  

Should we have a convention?

**Comment by JayyajGH** [comment]
Sorry I automatically flip into BEM convention when writing CSS.  Block__element--modifier.  It fits in really well with atomic css and utility first css etc. So for buttons for example would be:

.button for the base generic button stuff
.button--small, button--medium, button--large for the sizing
.button--primary, button--secondary, button--tertiary for the button type
.button__label, .button__icon etc. to refer to part of the button


https://css-tricks.com/bem-101/

**Comment by JayyajGH** [comment]
I think this style works really well with components as the block can be your component and the stuff that makes up the component are your elements.

**Comment by edwh** [comment]
Thank you - now I know.

The stuff itself looks fine, and better.  Ok to merge or are you still 
doing it?

------ Original Message ------

**Comment by JayyajGH** [comment]
https://www.youtube.com/watch?v=wFn5nel3j6w
https://speakerdeck.com/csswizardry/css-for-software-engineers-for-css-developers

This video is worth a worth.  I've seen Harry Roberts talk many times and I think he is probably the person that has taught me the most about CSS.  Not that BEM is his idea but this talk mentions using it in the atomic CSS style.  His general idea is CSS should be treated like any other programming language.  Single responsibility principle and all that. Classes should do one thing.  This is where the CSS utility frameworks like Tailwind come in which loads of people use with Vue.

**Comment by JayyajGH** [comment]
Happy to change the classes though if you would rather it fitted it better with the other CSS...

**Comment by JayyajGH** [comment]
This is complete for now.  There are other changes but they will be the 20% of the 80/20 rule!

**Comment by edwh** [comment]
It's a little inconcsistent with bootstrap, but it seems like a good 
rationale, so stick with it.

------ Original Message ------

**Comment by JayyajGH** [comment]
If you haven't seen it before then check out tailwind.  I'm still not sure how i feel about utility first css but it's getting more and more popular.  It's basically like bootstrap but without the opinionated components.

**Comment by edwh** [comment]
I like opinionated :-).  Someone else's considered choices are often better than my own floundering in a sea of options.

I'll check out the links, ta.

**Comment by JayyajGH** [comment]
I think my concern about these kind of frameworks is they almost discourage you from having consistent styles.  If you set up your component and styleguide well then you don't really need a lot of this stuff.  You probably shouldn't be randomly adding padding to an element etc.  Otherwise someone will use a component and add 10px and someone else will add 20px and you lose the consistency.

**Comment by JayyajGH** [comment]
I think my last comment sort of agreed with your last statement :-)

**Comment by JayyajGH** [comment]
When i add a button to a page then i don't want to worry about how much padding to give it and how to lay it out.  I want whatever the button component designer set it up to have. I want a medium sized primary button.  Full stop.  That button knows how much padding to have and how big the font is etc.

**Comment by edwh** [comment]
I agree about the padding kind of thing.  All that nonsense I did with 
b-row should have told me that I was doing the wrong thing by using 
those components.

------ Original Message ------

**Comment by JayyajGH** [comment]
Hindsight is a great thing!  In reality designing up front never works either as people change their minds.

**Comment by edwh** [comment]
Well, nothing actually works, does it?

------ Original Message ------

**Comment by edwh** [comment]
Very interesting talk indeed.

I think there's a key distinction he doesn't bring out, though.

If you're structuring your "stuff" (code, CSS, whatever) for an expert 
in that area who will be working on the internals, then you want to do 
all the kinds of stuff he talks about.  It makes your stuff better, 
makes it easier to maintain, etc.  He's quite right that these 
principles work in the CSS world too.  You could go further, though.  He 
is advocating are a whole bunch of principles for people to remember and 
apply; the lesson from the way other programming languages have 
developed is that you embody those principles into languages.  It would 
be a nice world where CSS was reduced to the status of assembly 
language, and you worked in higher level languages.  We're moving in 
that direction, but it seems to be slow in CSS, whereas if you look at 
the way raw JS has evolved into jQuery into React/Vue that side is 
moving faster.

However if you're providing your "stuff" to someone else, then it's a 
completely different situation.  It is about interface design (not 
visual interface, conceptual interface).  You could write an interface 
which exposes a zillion different options, and leave it up to the user 
to combine those in sensible and good combinations.  But most of those 
combinations will not be sensible and good.

"Gives you incredible opportunity and flexibility" sounds good, but it's 
passing the buck.  The example of Subway being able to make 6.4 billion 
different sandwiches shows that you've offloaded an infeasible amount of 
choice onto the user.  You'll get a better sandwich by going to a 
sandwich shop where someone who knows a lot about sandwiches has chosen 
a selection of good sandwich combinations.

The ways in which I've used low-level Bootstrap utility classes to 
construct higher level clickable components in ways that break 
accessibility is a good example of how if you present someone with a 
toolkit of components which all have a single clear purpose then they 
can combine them in dumb ways.

Restricting choice at the interface level means you won't make very bad 
choices.  You won't make very good choices either.  But if you're not an 
expert in that area, you're much more likely to make old bad choices 
than inspired new good choices.  Less choice means a better average 
outcome.

This is why Bootstrap (despite the above example) is great for people 
like me who are not CSS experts, because it provides an actual interface 
that means an idiot can't go too far wrong.  And tailwind is great for 
people who are CSS experts who want to use it to build an actual 
interface.  Opinionated is good at the interface level, and bad 
internally.

I'd argue that this distinction between interface design and internal 
design is, ironically, one of the lessons of software development which 
has not yet (IMNSHO) been properly absorbed by CSS folk.  Consequently 
CSS folk tend to impose internal complexity on external interfaces and 
think that it's freedom, when it's more likely to be chaos.

------ Original Message ------

**Comment by JayyajGH** [comment]
Really interesting discussion.  Yeah I'd completely agree with you on many points.  I take your main point to be that consumers of components shouldn't have too much control.  That should be left to the component (or system) designer.

The interfaces (visual) and interfaces (conceptual) should ideally be designed up front and set in (soft) stone.
A consumer of components shouldn't have to worry about colours and padding and positioning.  That should be defined at some higher level.  It's why I'm still
not entirely comfortable with the the utility driven CSS frameworks like Tailwind and to some extend Bootstrap too.  They give the consumer too much control and choice.
It starts off good - give me a variant success button. Great.  But then you can tweak the padding and the spacing and the colours etc.  It seems to miss the whole point.

I suppose I didn't take it that he was saying you should provide loads of different options to a consumer.  Buttons for example.  You might start with button--primary, 
button--secondary and button--tertiary.  I would probably keep those in a _buttons.scss file or something similiar.  A button component consumer wouldn't just create
buttons themselves.  This would then be up to that component designer to create a new button type if required like button--ghost.  It's great for the button designer to be able to create lots of options quickly and easily.  I guess the problem with CSS is that then presents the opportunity for the consumer to do it too. The fact that it is easy to override pretty much anything in CSS is almost it's downfall.  It's just a verbal contract.

I think if you use Bootstrap out of the box without really knowing CSS it's great.  I don't think you fit into that box though as (even though you say you don't) you actually know CSS pretty well.  That means you can easily tweak bits which I suppose starts to break the interface defined by Bootstrap.

**Comment by JayyajGH** [comment]
I think I might have mentioned this before but a few years back I tried to create a CSS "starter pack" which tried to address what we're talking about.  It set in stone font sizes, colours, padding for everything you would want to use.  You want to add a heading?  Well if you want a size 2 heading then you must have it with 15px padding under it.  It was meant to be that the consumer wouldn't really have to write much CSS themselves.  Although if they would still be technically able to override whatever they wanted.  The idea was that when you started a project you would add this package in, tweak the defaults to be what you wanted and then it just worked.

It's here if you were bored and wanted to take a look at any point:
https://github.com/JayyajGH/Sass-Boilerplate

**Comment by JayyajGH** [comment]
Styleguide driven development also goes some way to address this. But once again it's based on trust rather than anything secure.

**Comment by edwh** [comment]
I think he's mostly talking about how to write maintainable internals code here, so I'm criticising him for not giving a different talk, which is a bit silly.  

I think a lot of issues with CSS come from the fact that (in code terms) it readily enables spaghetti code where everyone is using global variables.  People are always going stand on each other's toes, and then you evolve complex conventions and coding standards to work around that.  

Really that is always going to be a problem as long as those kind of concepts like public and private aren't built into the language.  The CSS scoping trick in Vue components is a nice and useful hack, but those kind of features need to be compile-time errors in the language rather than optional best practice and bugs at run-time.  

But of course, that's why it's successful.  Sloppy languages like JS, PHP, CSS are great at conquering an evolving and open landscape, and then later on you tidy them up.  JS and PHP are getting there, CSS is still in a world where there are sheriffs trying to tame the Wild West.

I agree that in terms of CSS I fit with the "a little knowledge" cliche.  I know enough to pervert Bootstrap, but not enough to not need it :-).

**Comment by JayyajGH** [comment]
Another point we haven't talked about is that I think people see CSS as being "just a styling thing" and so people just knock up a complete mess because it's not seen as a "real" language.  The same as any programming language, if you aren't good at it then you create a mess in the same way as people would with C#.  In my head this is changing but that might just be because of the people that I follow on twitter etc.  It gives you a false sense of the world.

**Comment by edwh** [comment]
Yes, I think that's very true.  CSS is perceived as incidental - either 
your focus is the code, or your focus is the visual stuff, but you don't 
feel you need to focus on CSS.

That reminds me of this "Javascript: The Good Parts" talk, which is 
quite old, but I remember being excellent.  And funny:

"It's the only language, that I'm aware of, that people feel that they 
don't need to learn it before they start using it."

https://www.youtube.com/watch?v=hQVTIJBZook

------ Original Message ------

**Comment by JayyajGH** [comment]
I've never seen that talk but I have read the book.  It's very good.  I'll watch that later.  I find Crockford a bit like the author Richard Dawkins.  Loads of good points but they come across too extreme.

**Comment by JayyajGH** [comment]
The pluralsite course called the same thing is also very good.

**Pull request merged**
