### PR TITLE
Use bootstrap breakpoints

### PR DESCRIPTION
**Pull request by JayyajGH**
Use the bootstrap breakpoints where necessary.

I've added comments for other places to do this i.e. the profile classes.  I might break the profile image stuff out into a component next so I'll sort the breakpoints for those classes then.

### CODE REVIEW

**Comment by edwh** [comment]
Can you double-check these are the right way round?

In NewsThread @media (max-width: 992px) becomes @include 
media-breakpoint-up(lg).  My reading of 
https://getbootstrap.com/docs/4.3/layout/overview/ is that the -up means 
"from this breakpoint upwards", whereas max-width means downwards.

------ Original Message ------

**Comment by JayyajGH** [comment]
I tested that as well but still got it the wrong way around!  NewsThread should now be fixed.

**Comment by JayyajGH** [comment]
I re-checked NewsReply and it looks ok.  Although the leaf isn't in the right place in the smallest breakpoints but that's another issue.

**Comment by edwh** [comment]
Hmmm, I thought I'd fixed that recently.  Will refix.

------ Original Message ------

**Pull request merged**
