### PR TITLE
Accessibility and HTML improvements

### PR DESCRIPTION
**Pull request by JayyajGH**
Various accessibility and HTML improvements to the volunteer sidebar

- Remove block element within an inline element (h4 within a)
- The tabbing order was incorrect due to the button being floated
- The focus rectangle for the header was around the header and the button
- Add a meaningful aria label to the button rather than "Add"

### CODE REVIEW

**Comment by edwh** [comment]
Have you checked CommunityEventSidebar for similar stuff?

**Comment by JayyajGH** [comment]
oh yes, looks like it has the same issues.

**Comment by JayyajGH** [comment]
Is there an easy way to add community events without hacking them in in javascript?  I don't have the sidebar shown because there aren't any existing events.  Is that correct?

**Comment by edwh** [comment]
There's a fix I've done recently to force that sidebar to show, I think. 
  But you can go to the Events page from the navbar, and add from there.

------ Original Message ------

**Comment by JayyajGH** [comment]
I've now made the same changes to the other sidebar now too. 

There is still work to be done in this area.  The focus indicator isn't very good so needs a new colour and shape.  Also the events aren't very accessible in the sidebar.  Missing tab stops, non-accessible labels etc.  We should probably look into refactoring the common code between these out too.  I might look at some of those things next.

This is one good to go though.

**Comment by edwh** [comment]
Ta.  I'll review today.

------ Original Message ------

**Comment by edwh** [comment]
When you do look at these, be aware that there is at least one difference, which is that events must be on a specific group, but volunteer ops need not be and can be system wide.

**Pull request merged**
