### PR TITLE
Create sidebar components

### PR DESCRIPTION
**Pull request by JayyajGH**
The sidebars were duplicated in three different files so I`ve put them into components.  We could go further and create a common sidebar wrapper in the future...

### CODE REVIEW

**Comment by edwh** [comment]
I can see the reasoning for this.  However there are some more subtle 
cases.  For example on the Volunteer Opportunity page, I have been 
thinking we will probably still want to show the job ads in the right 
sidebar, but not the volunteer ops because that's in the central part.  
Similarly for Community Events pages.

So I think you probably need some props which allow you to turn on/off 
which components within the sidebar appear.

------ Original Message ------

**Comment by JayyajGH** [comment]
OK cool.  I`ll add some in.

**Comment by JayyajGH** [comment]
Do you want all sidebar sections to be controlled by props? i.e. currently all four?

**Comment by edwh** [comment]
Yeah, while you're in there.  Probably overkill for the left bottom box 
but might as well.

Thanks.

------ Original Message ------

**Comment by JayyajGH** [comment]
I`ve just done it for the right hand sidebar at the moment.  If we do it for the left then the menu section floats to the top which presents a new set of problems.

**Comment by edwh** [comment]
Ok, that's fine for now.

**Pull request merged**
