### PR TITLE
Feature/seo page tweaks

### PR DESCRIPTION
**Pull request by JayyajGH**
How about this?  I've tried to keep it subtle...

### CODE REVIEW

**Comment by JayyajGH** [comment]
The row of ten images looks a bit odd on a mobile too.  Do they need to be shown at all?  Or maybe reduce the number of them.  They are very small at the moment.

**Comment by edwh** [comment]
Yes, they probably look a bit odd on mobile.  I want to get across the 
impression that there's real stuff, and also put some different content 
on the pages to try to fool Google into not noticing they're the same.  
What would be nicer would be to show a different number based on screen 
size.

------ Original Message ------

**Comment by edwh** [comment]
The fade looks good, though; shall I take this as is?

**Comment by JayyajGH** [comment]
Yeah take this if you're happy with it.  It's not just fade though.  It's fade and slight scale.  These things are important. :-)

**Comment by JayyajGH** [comment]
I'll look at tweaking the mobile view tomorrow if I get 5 mins spare!

**Comment by edwh** [comment]
I did notice :-)

------ Original Message ------

**Pull request merged**
