### PR TITLE
Refactor some of the more complex logic in the HTML into computed props.

### PR DESCRIPTION
**Pull request by JayyajGH**
Some of the logic in the HTML in this component was complex and duplicated so I have refactored it out into computed props.  It makes the HTML much nicer to read now too.

### CODE REVIEW

**Comment by edwh** [comment]
Using computed properties is neater, thanks.

There's "myChatMessage" and "chatMessage theirs" vs "chatMessage mine".  It feels weird to have both of these - shouldn't we be consistent on whether we have a single class or multiple?

For the bits like this:

```
          <div class="chatMessageProfilePic">
            <div>
              <profile-image :image="me.profile.turl" class="ml-1 mb-1 mt-1 inline" is-thumbnail size="sm" />
            </div>
          </div>
```
...can't we lose some divs?  I can't see a good reason for some of the spans, either. 

(This is my mess, obvs.)

**Comment by JayyajGH** [comment]
Might be easiest if @aaronferris answers as he did the last round of refactoring here. I could just remove the extra div and rename the classes but I know this was a complex area and I didn't follow the original discussion thread that closely and I don't want to mess it up without fully understanding the issues.

It's also been in my head to refactor this section to not have the duplication of the two blocks.  i.e. just one block for profile pic and message and flip the order around with flexbox for yours/mine and then drive an overall class from the computed prop.

Maybe merge this PR and talk about a refactor independently?

**Comment by JayyajGH** [comment]
I've just knocked something up very roughly to show what I mean.  This isn't complete or indeed tested but it superficially does what I mean.  I'll create a draft PR...

**Comment by edwh** [comment]
> Maybe merge this PR and talk about a refactor independently?

Yes.

**Comment by JayyajGH** [comment]
There is now a draft PR to address some of the things discussed here...

**Pull request merged**
