### PR TITLE
Tweaks to the layout on group header

### PR DESCRIPTION
**Pull request by JayyajGH**
Thought I'd add this in here for discussion.

I've moved the volunteer avatars and the button below.  Currently there are two options where one uses the bootstrap card and another with just a line break.

Thoughts?

### CODE REVIEW

**Comment by edwh** [comment]
I think that is better and makes it look less cluttered on small screens.  

I prefer the version with an hr, rather than a card.  Add a colon after 'here'.

I still feel it needs a bit of something around the profile pictures, though.  You don't really know quite how many you're going to get, so there's something kind of incomplete about it.  I can't quite put my finger on it.  But this is better as it stands, so I'd take that.

**Comment by JayyajGH** [comment]
I've removed the other card option to make it easier to talk about.  And added a colon...

**Comment by JayyajGH** [comment]
I'll try and think of something else to help the profile pics.

**Comment by JayyajGH** [comment]
I still need to tidy this as well as there is commented out code etc.  I'll tidy it now and see if I can think of any other options.

**Comment by JayyajGH** [comment]
Ok I've now given it a bit of a tidy so I'll mark it as ready for review.  I can't currently think of any improvements to the pics but I can that could always be a phase 2 if we think of something.

**Pull request merged**
