### PR TITLE
Move the regular chat fetching into the store

### PR DESCRIPTION
**Pull request by JayyajGH**
Move the timer based chat fetches into the store.

### CODE REVIEW

**Review by edwh — COMMENTED** [review]
I think once you move this into the store it will start to run for ModTools as well, and therefore you'll need to make the equivalent changes to the modtools layout?

**Comment by JayyajGH** [comment]
I'm made the change to MT already but not created a PR for it. When I next switch the PC on then I'll add a PR and they can go together.

**Comment by JayyajGH** [comment]
I'll delete this PR and include these changes in the MT branch as that merge will be easier.

**Comment by JayyajGH** [comment]
@edwh - Thinking about this I don't think this would have automatically run for MT as it's an action in the store which would need dispatch to set it off.  The timer is created within the action.  Regardless I have now merged my two changes so I'll create a PR for the combined change.

**Comment by edwh** [comment]
I think you're right.

------ Original Message ------

**Pull request closed without merging**
