### PR TITLE
Chat menu refactoring for default and modtools layouts

### PR DESCRIPTION
**Pull request by JayyajGH**
- Tweaks to the chatmenu component so it's more generic
- Move chat fetching into the store rather than the layout components
- Use the chatmenu component from MT

### CODE REVIEW

**Comment by edwh** [comment]
On ModTools, the Chat option is always greyed out.

This is not your bug, but in ModTools the chat fetch ought to also include the little-used Mod2Mod chats.  Can you add that in?

Code looks ok.

**Comment by JayyajGH** [comment]
That's odd.  It wasn't like that before so I must have subsequently broken it.  I'll take a look.

Yup I'll add the other change in too.

**Comment by JayyajGH** [comment]
For the Mod2Mod change do you mean for everyone? 

Currently the chat types are: chattypes: ['User2User', 'User2Mod']

so do you mean just add Mod2Mod to that list?

**Comment by edwh** [comment]
No, that should only be added in the MT case.  So you may need to use 
rootGetters to access the modtools flag.

------ Original Message ------

**Comment by JayyajGH** [comment]
Ah ok  will do.

**Comment by JayyajGH** [comment]
OK I've now fixed the greyed out chat icon and also added in the extra chat type for mods.  The greyed out icon is a bit messy really.  I'm hoping in the near future it will be possible to have just one <nav-link> element here and not a choice of nav-link or anchor.

**Pull request merged**
