### PR TITLE
Better align the nav icons

### PR DESCRIPTION
**Pull request by JayyajGH**
This is an idea for how the navbar could be better laid out without crushing the longer text.  I've basically let flexbox deal with the layout.  This is currently untested but just to give an impression of how it will look.

### CODE REVIEW

**Comment by edwh** [comment]
You just think flex solves everything.

...because it does.  That seems much better.  I feel there must be a downside somewhere, but I've tried different sizes.

**Comment by JayyajGH** [comment]
Ha!  It just means you don't have to worry about it yourself or set any explicit sizes.  If you add a new item or change the text etc. then flexbox will just deal with the alignment without you having to change anything.

I think spending the last 5 years working on a CMS where you didn't know how many items were in a list and things would just get added/removed by a content editor meant that I became a big fan of flexbox!

I'll tidy this up then and test it in various sizes/devices.

**Comment by edwh** [comment]
You do have to care a bit about navbars though, because of the 
breakpoint where it switches to a dropdown menu.

------ Original Message ------

**Comment by JayyajGH** [comment]
Yeah I set a maxwidth on it so it still kept within the previous boundaries so it still worked with the switch.

**Comment by JayyajGH** [comment]
Had a busy afternoon so I'll look at this tomorrow...

**Comment by edwh** [comment]
I'll stop your pay cheque.

------ Original Message ------

**Comment by JayyajGH** [comment]
I've made a couple of tweaks and given it some testing and it looks good to me.

**Pull request merged**
