### PR TITLE
Remove the bootstrap rows to fix the mobile sizing issue.

### PR DESCRIPTION
**Pull request by JayyajGH**
Fix the mobile layout by replacing the bootstrap rows/cols with flexbox

### CODE REVIEW

**Comment by JayyajGH** [comment]
For now I have just placed the image underneath the text and left-aligned.  It was in a bit of a weird place before.  This is least fixed the left/right shimmy on mobile.

**Comment by edwh** [comment]
Same issue presumably applies to CommunityEvent - can you do that one 
too as part of this?

------ Original Message ------

**Comment by JayyajGH** [comment]
Was gonna look at that one next. Yup can do it as part of this (as long as it's not too weird). I thought I'd added a community event when I added the volunteer op.  Can you see if it's still pending moderation?

**Comment by JayyajGH** [comment]
Looks like exactly the same issue with that one so should be nice and easy

**Comment by edwh** [comment]
Nope, not there.

Shall I make you a mod on the Playground group, then you can approve 
your own?

------ Original Message ------

**Comment by JayyajGH** [comment]
Yeah if that's easy enough to do.  How do I get to the mod area?

**Comment by edwh** [comment]
Done.  Access via modtools.org or localhost:3000/modtools.

------ Original Message ------

**Comment by JayyajGH** [comment]
I'll try and not let the power go to my head. :-)

**Comment by JayyajGH** [comment]
That's events sorted now too.

**Pull request merged**
